'''
Constants used by report filters

Created on Jul 11, 2013

@author: tosako
'''

YES = 'Y'
NO = 'N'
NOT_STATED = 'NS'
NONE = 'NONE'


DEMOGRAPHICS_PROGRAM_504 = 'dmgPrg504'
DEMOGRAPHICS_PROGRAM_IEP = 'dmgPrgIep'
DEMOGRAPHICS_PROGRAM_LEP = 'dmgPrgLep'
DEMOGRAPHICS_PROGRAM_TT1 = 'dmgPrgTt1'

DEMOGRAPHICS_ETHNICITY_AMERICAN = 'dmgEthAmi'
DEMOGRAPHICS_ETHNICITY_ASIAN = 'dmgEthAsn'
DEMOGRAPHICS_ETHNICITY_BLACK = 'dmgEthNBlk'
DEMOGRAPHICS_ETHNICITY_HISPANIC = 'dmgEthHsp'
DEMOGRAPHICS_ETHNICITY_PACIFIC = 'dmgEthPcf'
DEMOGRAPHICS_ETHNICITY_WHITE = 'dmgEthWht'
# Two or more races
DEMOGRAPHICS_ETHNICITY_MULTI = 'dmgEthMulti'

GRADE = 'grade'
ETHNICITY = 'ethnicity'
