'''
Created on Jul 11, 2013

@author: tosako
'''

YES = 'Y'
NO = 'N'
NOT_STATED = 'NS'
NONE = 'NONE'

TWO = 'TWO'

DEMOGRAPHICS_PROGRAM_504 = 'dmgPrg504'
DEMOGRAPHICS_PROGRAM_IEP = 'dmgPrgIep'
DEMOGRAPHICS_PROGRAM_LEP = 'dmgPrgLep'

DEMOGRAPHICS_ETHNICITY_HISPANIC = 'dmg_eth_hsp'
DEMOGRAPHICS_ETHNICITY_AMERICAN = 'dmg_eth_ami'
DEMOGRAPHICS_ETHNICITY_ASIAN = 'dmg_eth_asn'
DEMOGRAPHICS_ETHNICITY_BLACK = 'dmg_eth_blk'
DEMOGRAPHICS_ETHNICITY_PACIFIC = 'dmg_eth_pcf'
DEMOGRAPHICS_ETHNICITY_WHITE = 'dmg_eth_wht'

GRADE = 'grade'
ETHNICITY = 'ethnicity'
