'''
Constants used by report filters

Created on Jul 11, 2013

@author: tosako
'''

YES = 'Y'
NO = 'N'
NOT_STATED = 'NS'
NONE = 'NONE'


DEMOGRAPHICS_PROGRAM_504 = 'dmgPrg504'
DEMOGRAPHICS_PROGRAM_IEP = 'dmgPrgIep'
DEMOGRAPHICS_PROGRAM_LEP = 'dmgPrgLep'
DEMOGRAPHICS_PROGRAM_TT1 = 'dmgPrgTt1'

DEMOGRAPHICS_ETHNICITY_AMERICAN = '4'
DEMOGRAPHICS_ETHNICITY_ASIAN = '2'
DEMOGRAPHICS_ETHNICITY_BLACK = '1'
DEMOGRAPHICS_ETHNICITY_HISPANIC = '3'
DEMOGRAPHICS_ETHNICITY_PACIFIC = '5'
DEMOGRAPHICS_ETHNICITY_WHITE = '6'
# Two or more races
DEMOGRAPHICS_ETHNICITY_MULTI = '7'
DEMOGRAPHICS_ETHNICITY_NOT_STATED = '0'

GRADE = 'grade'
ETHNICITY = 'ethnicity'
