'''
Created on Mar 12, 2013

@author: dip
'''


class AssessmentType():
    '''
    constants for asmt types
    '''
    SUMMATIVE = 'SUMMATIVE'
    INTERIM_COMPREHENSIVE = 'INTERIM COMPREHENSIVE'


class Constants():
    '''
    constants for reports
    '''

    SL = 'sl'
    PDF = 'pdf'
    LANG = 'lang'
    GRAYSCALE = 'grayscale'
    STATECODE = 'stateCode'
    DISTRICTGUID = 'districtGuid'
    SCHOOLGUID = 'schoolGuid'
    STUDENTGUID = 'studentGuid'
    ASMTSUBJECT = 'asmtSubject'
    ASMT_SUBJECT = 'asmt_subject'
    ASMTTYPE = 'asmtType'
    ASMTYEAR = 'asmtYear'
    ASMTGUID = 'asmtGuid'
    ASMT_TYPE = 'asmt_type'
    ASMT_GRADE = 'asmt_grade'
    ASMT_GRADE_NAME = 'asmt_grade_name'
    ASMT_GUID = 'asmt_guid'
    ASMT_REC_ID = 'asmt_rec_id'
    ASMTGRADE = 'asmtGrade'
    ASSESSMENTGUID = 'assessmentGuid'
    STATE_NAME = 'state_name'
    STATE_CODE = 'state_code'
    DISTRICT_NAME = 'district_name'
    DISTRICT_GUID = 'district_guid'
    SCHOOL_NAME = 'school_name'
    SCHOOL_GUID = 'school_guid'
    SECTION_GUID = 'section_guid'
    STUDENT_GUID = 'student_guid'
    GUID = 'guid'
    PERCENTAGE = 'percentage'
    COUNT = 'count'
    INTERVALS = 'intervals'
    INST_HIER_REC_ID = 'inst_hier_rec_id'
    LEVEL = 'level'
    TOTAL = 'total'
    TOTAL_MATH = 'total_math'
    TOTAL_ELA = 'total_ela'
    SCORE_BUCKET = 'score_bucket'
    UNFILTERED_TOTAL = 'unfilteredTotal'
    NAME = 'name'
    ID = 'id'
    HASINTERIM = 'hasInterim'
    ROWID = 'rowId'
    RESULTS = 'results'
    DIM_INST_HIER = 'dim_inst_hier'
    DIM_ASMT = 'dim_asmt'
    DIM_STAFF = 'dim_staff'
    DIM_STUDENT = 'dim_student'
    FACT_ASMT_OUTCOME = 'fact_asmt_outcome'
    USER_MAPPING = 'user_mapping'
    CUSTOM_METADATA = 'custom_metadata'
    ASMT_CUSTOM_METADATA = 'asmt_custom_metadata'
    MIN_CELL_SIZE = "min_cell_size"
    MATH = 'Math'
    ELA = 'ELA'
    SUBJECTS = 'subjects'
    SUBJECT1 = 'subject1'
    SUBJECT2 = 'subject2'
    METADATA = 'metadata'
    COLORS = 'colors'
    SUMMARY = 'summary'
    RECORDS = 'records'
    CONTEXT = 'context'
    PARAMS = 'params'
    GRADE = 'Grade'
    DISPLAY_LEVEL = 'display_level'
    ASMT_PERIOD_YEAR = 'asmt_period_year'
    DMG_ETH_HSP = 'dmg_eth_hsp'
    DMG_ETH_AMI = 'dmg_eth_ami'
    DMG_ETH_ASN = 'dmg_eth_asn'
    DMG_ETH_BLK = 'dmg_eth_blk'
    DMG_ETH_PCF = 'dmg_eth_pcf'
    DMG_ETH_WHT = 'dmg_eth_wht'
    NOT_STATED = 'not_stated'
    RAW_EXPORT = 'raw'
    MOST_RECENT = 'most_recent'
    ASMT_YEAR = 'asmt_year'
