// Generated by CoffeeScript 1.4.0
(function() {
  var accumulate, attendees, attendees_counter, client_script, coffee, count_using_file, friends, friends_counter, fs, http, read_file, server, split, sum, view;

  fs = require('fs');

  http = require('http');

  coffee = require('coffee-script');

  attendees = 0;

  friends = 0;

  split = function(text) {
    return text.split(/,/g);
  };

  accumulate = function(initial, numbers, accumulator) {
    var number, total, _i, _len;
    total = initial || 0;
    for (_i = 0, _len = numbers.length; _i < _len; _i++) {
      number = numbers[_i];
      total = accumulator(total, number);
    }
    return total;
  };

  sum = function(accum, current) {
    return accum + current;
  };

  attendees_counter = function(data) {
    return attendees = data.split(/,/).length;
  };

  friends_counter = function(data) {
    var numbers, string;
    numbers = (function() {
      var _i, _len, _ref, _results;
      _ref = split(data);
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        string = _ref[_i];
        _results.push(parseInt(string));
      }
      return _results;
    })();
    return friends = accumulate(0, numbers, sum);
  };

  read_file = function(file, strategy) {
    return fs.readFile(file, 'utf-8', function(error, response) {
      if (error) {
        throw error;
      }
      return strategy(response);
    });
  };

  count_using_file = function(file, strategy) {
    read_file(file, strategy);
    return fs.watchFile(file, (function() {
      return read_file(file, strategy);
    }));
  };

  count_using_file('partygoers.txt', attendees_counter);

  count_using_file('friends.txt', friends_counter);

  server = http.createServer(function(request, response) {
    switch (request.url) {
      case '/':
        response.writeHead(200, {
          'Content-Type': 'text/html'
        });
        return response.end(view);
      case '/count':
        response.writeHead(200, {
          'Content-Type': 'text/plain'
        });
        return response.end("" + (attendees + friends));
    }
  });

  server.listen(8080, '127.0.0.1');

  client_script = coffee.compile('showAttendees = ->\n  $.get "/count", (response) ->\n    $("#how-many-attendees").html("#{response} attendees!")\nshowAttendees()\nsetInterval showAttendees, 1000 ');

  view = "<!doctype html>\n<title>How many people are coming?</title>\n<body>\n<div id='how-many-attendees'></div>\n<script src='http://code.jquery.com/jquery-1.6.2.js'></script> #11 <script> #11 " + client_script + " #11 </script> #11 ";

}).call(this);
