'''
Created on May 9, 2013

@author: dip
'''


class RolesConstants():
    '''
    Defined roles
    '''
    DEPLOYMENT_ADMINISTRATOR = 'DEPLOYMENT_ADMINISTRATOR'
    SYSTEM_ADMINISTRATOR = 'SYSTEM_ADMINISTRATOR'
    DATA_LOADER = 'DATA_LOADER'
    DATA_CORRECTOR = 'DATA_CORRECTOR'
    PSYCHOMETRICIAN = 'PSYCHOMETRICIAN'
    NO_ROLE = 'NO_ROLE'
    STATE_DATA_EXTRACTOR = 'STATE_DATA_EXTRACTOR'
    HIGHER_EDUCATION_ADMISSIONS_OFFICER = 'HIGHER_EDUCATION_ADMISSIONS_OFFICER'
    STUDENT = 'STUDENT'
    PARENT = 'PARENT'
    TEACHER = 'TEACHER'
    SCHOOL_EDUCATION_ADMINISTRATOR_1 = 'SCHOOL_EDUCATION_ADMINISTRATOR_1'
    SCHOOL_EDUCATION_ADMINISTRATOR_2 = 'SCHOOL_EDUCATION_ADMINISTRATOR_2'
    DISTRICT_EDUCATION_ADMINISTRATOR_1 = 'DISTRICT_EDUCATION_ADMINISTRATOR_1'
    DISTRICT_EDUCATION_ADMINISTRATOR_2 = 'DISTRICT_EDUCATION_ADMINISTRATOR_2'
    STATE_EDUCATION_ADMINISTRATOR_1 = 'STATE_EDUCATION_ADMINISTRATOR_1'
    STATE_EDUCATION_ADMINISTRATOR_2 = 'STATE_EDUCATION_ADMINISTRATOR_2'
    CONSORTIUM_EDUCATION_ADMINISTRATOR_1 = 'CONSORTIUM_EDUCATION_ADMINISTRATOR_1'
    CONSORTIUM_EDUCATION_ADMINISTRATOR_2 = 'CONSORTIUM_EDUCATION_ADMINISTRATOR_2'
    # For no role in memberOf in SAML response
    NONE = 'NONE'
