# transformation rules
CLEAN = 'clean'
CLEAN_UP = 'cleanUpper'
DATE = 'date'
SCHOOL_TY = 'schoolType'
SEX = 'sex'
YN = 'yn'

COLUMNS = ('phase', 'source_table', 'source_column', 'target_table', 'target_column', 'transformation_rule', 'stored_proc_name')

op_table_conf = {
    'int_sbac_asmt_outcome',
    'stg_sbac_asmt_outcome'
}

ref_table_conf = {
    'column_definitions': COLUMNS,
    'column_mappings': [
        # Columns:
        # column_map_key, phase, source_table, source_column, target_table, target_column, transformation_rule, stored_proc_name, stored_proc_created_date, created_date

        # json to int_sbac_asmt
        ('1', 'lz_json', 'Identification.Guid', 'int_sbac_asmt', 'guid_asmt', None, 'substr({value}, 1, {length})'),
        ('1', 'lz_json', 'Claims.Claim1.Name', 'int_sbac_asmt', 'name_claim_1', None, 'substr({value}, 1, {length})'),
        ('1', 'lz_json', 'Claims.Claim2.Name', 'int_sbac_asmt', 'name_claim_2', None, 'substr({value}, 1, {length})'),
        ('1', 'lz_json', 'Claims.Claim3.Name', 'int_sbac_asmt', 'name_claim_3', None, 'substr({value}, 1, {length})'),
        ('1', 'lz_json', 'Claims.Claim4.Name', 'int_sbac_asmt', 'name_claim_4', None, 'substr({value}, 1, {length})'),
        ('1', 'lz_json', 'PerformanceLevels.Level1.Name', 'int_sbac_asmt', 'name_perf_lvl_1', None, 'substr({value}, 1, {length})'),
        ('1', 'lz_json', 'PerformanceLevels.Level2.Name', 'int_sbac_asmt', 'name_perf_lvl_2', None, 'substr({value}, 1, {length})'),
        ('1', 'lz_json', 'PerformanceLevels.Level3.Name', 'int_sbac_asmt', 'name_perf_lvl_3', None, 'substr({value}, 1, {length})'),
        ('1', 'lz_json', 'PerformanceLevels.Level4.Name', 'int_sbac_asmt', 'name_perf_lvl_4', None, 'substr({value}, 1, {length})'),
        ('1', 'lz_json', 'PerformanceLevels.Level5.Name', 'int_sbac_asmt', 'name_perf_lvl_5', None, 'substr({value}, 1, {length})'),
        ('1', 'lz_json', 'ClaimsPerformanceLevel.Level1.Name', 'int_sbac_asmt', 'asmt_claim_perf_lvl_name_1', None, 'substr({value}, 1, {length})'),
        ('1', 'lz_json', 'ClaimsPerformanceLevel.Level2.Name', 'int_sbac_asmt', 'asmt_claim_perf_lvl_name_2', None, 'substr({value}, 1, {length})'),
        ('1', 'lz_json', 'ClaimsPerformanceLevel.Level3.Name', 'int_sbac_asmt', 'asmt_claim_perf_lvl_name_3', None, 'substr({value}, 1, {length})'),
        ('1', 'lz_json', 'Identification.Period', 'int_sbac_asmt', 'period', None, 'substr({value}, 1, {length})'),
        ('1', 'lz_json', 'Claims.Claim1.MaxScore', 'int_sbac_asmt', 'score_claim_1_max', None, "to_number({value},'9999')"),
        ('1', 'lz_json', 'Claims.Claim1.MinScore', 'int_sbac_asmt', 'score_claim_1_min', None, "to_number({value},'9999')"),
        ('1', 'lz_json', 'Claims.Claim2.MaxScore', 'int_sbac_asmt', 'score_claim_2_max', None, "to_number({value},'9999')"),
        ('1', 'lz_json', 'Claims.Claim2.MinScore', 'int_sbac_asmt', 'score_claim_2_min', None, "to_number({value},'9999')"),
        ('1', 'lz_json', 'Claims.Claim3.MaxScore', 'int_sbac_asmt', 'score_claim_3_max', None, "to_number({value},'9999')"),
        ('1', 'lz_json', 'Claims.Claim3.MinScore', 'int_sbac_asmt', 'score_claim_3_min', None, "to_number({value},'9999')"),
        ('1', 'lz_json', 'Claims.Claim4.MaxScore', 'int_sbac_asmt', 'score_claim_4_max', None, "to_number({value},'9999')"),
        ('1', 'lz_json', 'Claims.Claim4.MinScore', 'int_sbac_asmt', 'score_claim_4_min', None, "to_number({value},'9999')"),
        ('1', 'lz_json', 'PerformanceLevels.Level2.CutPoint', 'int_sbac_asmt', 'score_cut_point_1', None, "to_number({value},'9999')"),
        ('1', 'lz_json', 'PerformanceLevels.Level3.CutPoint', 'int_sbac_asmt', 'score_cut_point_2', None, "to_number({value},'9999')"),
        ('1', 'lz_json', 'PerformanceLevels.Level4.CutPoint', 'int_sbac_asmt', 'score_cut_point_3', None, "to_number({value},'9999')"),
        ('1', 'lz_json', 'PerformanceLevels.Level5.CutPoint', 'int_sbac_asmt', 'score_cut_point_4', None, "to_number({value},'9999')"),
        ('1', 'lz_json', 'Overall.MaxScore', 'int_sbac_asmt', 'score_overall_max', None, "to_number({value},'9999')"),
        ('1', 'lz_json', 'Overall.MinScore', 'int_sbac_asmt', 'score_overall_min', None, "to_number({value},'9999')"),
        ('1', 'lz_json', 'Identification.Subject', 'int_sbac_asmt', 'subject', 'subjectType', None),
        ('1', 'lz_json', 'Identification.Type', 'int_sbac_asmt', 'type', 'asmtType', None),
        ('1', 'lz_json', 'Identification.Version', 'int_sbac_asmt', 'version', 'clean', None),
        ('1', 'lz_json', 'Identification.Year', 'int_sbac_asmt', 'year', None, "to_number({value},'9999')"),
        ('1', 'lz_json', 'Identification.EffectiveDate', 'int_sbac_asmt', 'effective_date', 'clean', None),
        # CSV to staging
        ('1', 'lz_csv', 'StateAbbreviation', 'stg_sbac_asmt_outcome', 'StateAbbreviation', 'cleanUpper', None),
        ('1', 'lz_csv', 'ResponsibleDistrictIdentifier', 'stg_sbac_asmt_outcome', 'ResponsibleDistrictIdentifier', 'clean', None),
        ('1', 'lz_csv', 'OrganizationName', 'stg_sbac_asmt_outcome', 'OrganizationName', 'clean', None),
        ('1', 'lz_csv', 'ResponsibleSchoolIdentifier', 'stg_sbac_asmt_outcome', 'ResponsibleSchoolIdentifier', 'clean', None),
        ('1', 'lz_csv', 'NameOfInstitution', 'stg_sbac_asmt_outcome', 'NameOfInstitution', 'clean', None),
        ('1', 'lz_csv', 'StudentIdentifier', 'stg_sbac_asmt_outcome', 'StudentIdentifier', 'clean', None),
        ('1', 'lz_csv', 'ExternalSSID', 'stg_sbac_asmt_outcome', 'ExternalSSID', 'clean', None),
        ('1', 'lz_csv', 'FirstName', 'stg_sbac_asmt_outcome', 'FirstName', 'clean', None),
        ('1', 'lz_csv', 'MiddleName', 'stg_sbac_asmt_outcome', 'MiddleName', 'clean', None),
        ('1', 'lz_csv', 'LastOrSurname', 'stg_sbac_asmt_outcome', 'LastOrSurname', 'clean', None),
        ('1', 'lz_csv', 'Sex', 'stg_sbac_asmt_outcome', 'Sex', 'gender', None),
        ('1', 'lz_csv', 'Birthdate', 'stg_sbac_asmt_outcome', 'Birthdate', 'date', None),
        ('1', 'lz_csv', 'GradeLevelWhenAssessed', 'stg_sbac_asmt_outcome', 'GradeLevelWhenAssessed', 'clean', None),
        ('1', 'lz_csv', 'HispanicOrLatinoEthnicity', 'stg_sbac_asmt_outcome', 'HispanicOrLatinoEthnicity', 'yn', None),
        ('1', 'lz_csv', 'AmericanIndianOrAlaskaNative', 'stg_sbac_asmt_outcome', 'AmericanIndianOrAlaskaNative', 'yn', None),
        ('1', 'lz_csv', 'Asian', 'stg_sbac_asmt_outcome', 'Asian', 'yn', None),
        ('1', 'lz_csv', 'BlackOrAfricanAmerican', 'stg_sbac_asmt_outcome', 'BlackOrAfricanAmerican', 'yn', None),
        ('1', 'lz_csv', 'NativeHawaiianOrOtherPacificIslander', 'stg_sbac_asmt_outcome', 'NativeHawaiianOrOtherPacificIslander', 'yn', None),
        ('1', 'lz_csv', 'White', 'stg_sbac_asmt_outcome', 'White', 'yn', None),
        ('1', 'lz_csv', 'DemographicRaceTwoOrMoreRaces', 'stg_sbac_asmt_outcome', 'DemographicRaceTwoOrMoreRaces', 'yn', None),
        ('1', 'lz_csv', 'IDEAIndicator', 'stg_sbac_asmt_outcome', 'IDEAIndicator', 'yn', None),
        ('1', 'lz_csv', 'LEPStatus', 'stg_sbac_asmt_outcome', 'LEPStatus', 'yn', None),
        ('1', 'lz_csv', 'Section504Status', 'stg_sbac_asmt_outcome', 'Section504Status', 'yn', None),
        ('1', 'lz_csv', 'EconomicDisadvantageStatus', 'stg_sbac_asmt_outcome', 'EconomicDisadvantageStatus', 'yn', None),
        ('1', 'lz_csv', 'MigrantStatus', 'stg_sbac_asmt_outcome', 'MigrantStatus', 'yn', None),
        ('1', 'lz_csv', 'Group1Id', 'stg_sbac_asmt_outcome', 'Group1Id', 'clean', None),
        ('1', 'lz_csv', 'Group1Text', 'stg_sbac_asmt_outcome', 'Group1Text', 'clean', None),
        ('1', 'lz_csv', 'Group2Id', 'stg_sbac_asmt_outcome', 'Group2Id', 'clean', None),
        ('1', 'lz_csv', 'Group2Text', 'stg_sbac_asmt_outcome', 'Group2Text', 'clean', None),
        ('1', 'lz_csv', 'AssessmentGuid', 'stg_sbac_asmt_outcome', 'AssessmentGuid', 'clean', None),
        ('1', 'lz_csv', 'AssessmentSessionLocationId', 'stg_sbac_asmt_outcome', 'AssessmentSessionLocationId', 'clean', None),
        ('1', 'lz_csv', 'AssessmentSessionLocation', 'stg_sbac_asmt_outcome', 'AssessmentSessionLocation', 'clean', None),
        ('1', 'lz_csv', 'AssessmentAdministrationFinishDate', 'stg_sbac_asmt_outcome', 'AssessmentAdministrationFinishDate', 'date', None),
        ('1', 'lz_csv', 'AssessmentYear', 'stg_sbac_asmt_outcome', 'AssessmentYear', 'clean', None),
        ('1', 'lz_csv', 'AssessmentType', 'stg_sbac_asmt_outcome', 'AssessmentType', 'asmtType', None),
        ('1', 'lz_csv', 'AssessmentAcademicSubject', 'stg_sbac_asmt_outcome', 'AssessmentAcademicSubject', 'subjectType', None),
        ('1', 'lz_csv', 'AssessmentLevelForWhichDesigned', 'stg_sbac_asmt_outcome', 'AssessmentLevelForWhichDesigned', 'clean', None),
        ('1', 'lz_csv', 'AssessmentSubtestResultScoreValue', 'stg_sbac_asmt_outcome', 'AssessmentSubtestResultScoreValue', 'clean', None),
        ('1', 'lz_csv', 'AssessmentSubtestMinimumValue', 'stg_sbac_asmt_outcome', 'AssessmentSubtestMinimumValue', 'clean', None),
        ('1', 'lz_csv', 'AssessmentSubtestMaximumValue', 'stg_sbac_asmt_outcome', 'AssessmentSubtestMaximumValue', 'clean', None),
        ('1', 'lz_csv', 'AssessmentPerformanceLevelIdentifier', 'stg_sbac_asmt_outcome', 'AssessmentPerformanceLevelIdentifier', 'clean', None),
        ('1', 'lz_csv', 'AssessmentSubtestResultScoreClaim1Value', 'stg_sbac_asmt_outcome', 'AssessmentSubtestResultScoreClaim1Value', 'clean', None),
        ('1', 'lz_csv', 'AssessmentSubtestClaim1MinimumValue', 'stg_sbac_asmt_outcome', 'AssessmentSubtestClaim1MinimumValue', 'clean', None),
        ('1', 'lz_csv', 'AssessmentSubtestClaim1MaximumValue', 'stg_sbac_asmt_outcome', 'AssessmentSubtestClaim1MaximumValue', 'clean', None),
        ('1', 'lz_csv', 'AssessmentClaim1PerformanceLevelIdentifier', 'stg_sbac_asmt_outcome', 'AssessmentSubtestClaim1PerformanceLevelIdentifier', 'clean', None),
        ('1', 'lz_csv', 'AssessmentSubtestResultScoreClaim2Value', 'stg_sbac_asmt_outcome', 'AssessmentSubtestResultScoreClaim2Value', 'clean', None),
        ('1', 'lz_csv', 'AssessmentSubtestClaim2MinimumValue', 'stg_sbac_asmt_outcome', 'AssessmentSubtestClaim2MinimumValue', 'clean', None),
        ('1', 'lz_csv', 'AssessmentSubtestClaim2MaximumValue', 'stg_sbac_asmt_outcome', 'AssessmentSubtestClaim2MaximumValue', 'clean', None),
        ('1', 'lz_csv', 'AssessmentClaim2PerformanceLevelIdentifier', 'stg_sbac_asmt_outcome', 'AssessmentSubtestClaim2PerformanceLevelIdentifier', 'clean', None),
        ('1', 'lz_csv', 'AssessmentSubtestResultScoreClaim3Value', 'stg_sbac_asmt_outcome', 'AssessmentSubtestResultScoreClaim3Value', 'clean', None),
        ('1', 'lz_csv', 'AssessmentSubtestClaim3MinimumValue', 'stg_sbac_asmt_outcome', 'AssessmentSubtestClaim3MinimumValue', 'clean', None),
        ('1', 'lz_csv', 'AssessmentSubtestClaim3MaximumValue', 'stg_sbac_asmt_outcome', 'AssessmentSubtestClaim3MaximumValue', 'clean', None),
        ('1', 'lz_csv', 'AssessmentClaim3PerformanceLevelIdentifier', 'stg_sbac_asmt_outcome', 'AssessmentSubtestClaim3PerformanceLevelIdentifier', 'clean', None),
        ('1', 'lz_csv', 'AssessmentSubtestResultScoreClaim4Value', 'stg_sbac_asmt_outcome', 'AssessmentSubtestResultScoreClaim4Value', 'clean', None),
        ('1', 'lz_csv', 'AssessmentSubtestClaim4MinimumValue', 'stg_sbac_asmt_outcome', 'AssessmentSubtestClaim4MinimumValue', 'clean', None),
        ('1', 'lz_csv', 'AssessmentSubtestClaim4MaximumValue', 'stg_sbac_asmt_outcome', 'AssessmentSubtestClaim4MaximumValue', 'clean', None),
        ('1', 'lz_csv', 'AssessmentClaim4PerformanceLevelIdentifier', 'stg_sbac_asmt_outcome', 'AssessmentSubtestClaim4PerformanceLevelIdentifier', 'clean', None),
        ('1', 'lz_csv', 'AccommodationAmericanSignLanguage', 'stg_sbac_asmt_outcome', 'AccommodationAmericanSignLanguage', 'clean', None),
        ('1', 'lz_csv', 'AccommodationSignLanguageHumanIntervention', 'stg_sbac_asmt_outcome', 'AccommodationSignLanguageHumanIntervention', 'clean', None),
        ('1', 'lz_csv', 'AccommodationBraille', 'stg_sbac_asmt_outcome', 'AccommodationBraille', 'clean', None),
        ('1', 'lz_csv', 'AccommodationClosedCaptioning', 'stg_sbac_asmt_outcome', 'AccommodationClosedCaptioning', 'clean', None),
        ('1', 'lz_csv', 'AccommodationTextToSpeech', 'stg_sbac_asmt_outcome', 'AccommodationTextToSpeech', 'clean', None),
        ('1', 'lz_csv', 'AccommodationAbacus', 'stg_sbac_asmt_outcome', 'AccommodationAbacus', 'clean', None),
        ('1', 'lz_csv', 'AccommodationAlternateResponseOptions', 'stg_sbac_asmt_outcome', 'AccommodationAlternateResponseOptions', 'clean', None),
        ('1', 'lz_csv', 'AccommodationCalculator', 'stg_sbac_asmt_outcome', 'AccommodationCalculator', 'clean', None),
        ('1', 'lz_csv', 'AccommodationMultiplicationTable', 'stg_sbac_asmt_outcome', 'AccommodationMultiplicationTable', 'clean', None),
        ('1', 'lz_csv', 'AccommodationPrintOnDemand', 'stg_sbac_asmt_outcome', 'AccommodationPrintOnDemand', 'clean', None),
        ('1', 'lz_csv', 'AccommodationReadAloud', 'stg_sbac_asmt_outcome', 'AccommodationReadAloud', 'clean', None),
        ('1', 'lz_csv', 'AccommodationScribe', 'stg_sbac_asmt_outcome', 'AccommodationScribe', 'clean', None),
        ('1', 'lz_csv', 'AccommodationSpeechToText', 'stg_sbac_asmt_outcome', 'AccommodationSpeechToText', 'clean', None),
        ('1', 'lz_csv', 'AccommodationStreamlineMode', 'stg_sbac_asmt_outcome', 'AccommodationStreamlineMode', 'clean', None),
        ('1', 'lz_csv', 'Op', 'stg_sbac_asmt_outcome', 'op', 'option', None),
        # Staging to Integration
        ('3', 'stg_sbac_asmt_outcome', 'record_sid', 'int_sbac_asmt_outcome', 'record_sid', None, None),
        ('3', 'stg_sbac_asmt_outcome', 'guid_batch', 'int_sbac_asmt_outcome', 'guid_batch', None, None),
        ('3', 'stg_sbac_asmt_outcome', 'Op', 'int_sbac_asmt_outcome', 'op', None, None),
        ('3', 'stg_sbac_asmt_outcome', 'StateAbbreviation', 'int_sbac_asmt_outcome', 'code_state', None, 'substr({src_column}, 1, {length})'),
        ('3', 'stg_sbac_asmt_outcome', 'ResponsibleDistrictIdentifier', 'int_sbac_asmt_outcome', 'guid_district', None, 'substr({src_column}, 1, {length})'),
        ('3', 'stg_sbac_asmt_outcome', 'OrganizationName', 'int_sbac_asmt_outcome', 'name_district', None, 'substr({src_column}, 1, {length})'),
        ('3', 'stg_sbac_asmt_outcome', 'ResponsibleSchoolIdentifier', 'int_sbac_asmt_outcome', 'guid_school', None, 'substr({src_column}, 1, {length})'),
        ('3', 'stg_sbac_asmt_outcome', 'NameOfInstitution', 'int_sbac_asmt_outcome', 'name_school', None, 'substr({src_column}, 1, {length})'),
        ('3', 'stg_sbac_asmt_outcome', 'StudentIdentifier', 'int_sbac_asmt_outcome', 'guid_student', None, 'substr({src_column}, 1, {length})'),
        ('3', 'stg_sbac_asmt_outcome', 'ExternalSSID', 'int_sbac_asmt_outcome', 'external_student_id', None, 'substr({src_column}, 1, {length})'),
        ('3', 'stg_sbac_asmt_outcome', 'FirstName', 'int_sbac_asmt_outcome', 'name_student_first', None, 'substr({src_column}, 1, {length})'),
        ('3', 'stg_sbac_asmt_outcome', 'MiddleName', 'int_sbac_asmt_outcome', 'name_student_middle', None, 'substr({src_column}, 1, {length})'),
        ('3', 'stg_sbac_asmt_outcome', 'LastOrSurname', 'int_sbac_asmt_outcome', 'name_student_last', None, 'substr({src_column}, 1, {length})'),
        ('3', 'stg_sbac_asmt_outcome', 'Sex', 'int_sbac_asmt_outcome', 'sex_student', None, 'substr({src_column}, 1, {length})'),
        ('3', 'stg_sbac_asmt_outcome', 'Birthdate', 'int_sbac_asmt_outcome', 'birthdate_student', None, 'substr({src_column}, 1, {length})'),
        ('3', 'stg_sbac_asmt_outcome', 'GradeLevelWhenAssessed', 'int_sbac_asmt_outcome', 'grade_enrolled', None, 'substr({src_column}, 1, {length})'),
        ('3', 'stg_sbac_asmt_outcome', 'HispanicOrLatinoEthnicity', 'int_sbac_asmt_outcome', 'dmg_eth_hsp', None, 'cast({src_column} as bool)'),
        ('3', 'stg_sbac_asmt_outcome', 'AmericanIndianOrAlaskaNative', 'int_sbac_asmt_outcome', 'dmg_eth_ami', None, 'cast({src_column} as bool)'),
        ('3', 'stg_sbac_asmt_outcome', 'Asian', 'int_sbac_asmt_outcome', 'dmg_eth_asn', None, 'cast({src_column} as bool)'),
        ('3', 'stg_sbac_asmt_outcome', 'BlackOrAfricanAmerican', 'int_sbac_asmt_outcome', 'dmg_eth_blk', None, 'cast({src_column} as bool)'),
        ('3', 'stg_sbac_asmt_outcome', 'NativeHawaiianOrOtherPacificIslander', 'int_sbac_asmt_outcome', 'dmg_eth_pcf', None, 'cast({src_column} as bool)'),
        ('3', 'stg_sbac_asmt_outcome', 'White', 'int_sbac_asmt_outcome', 'dmg_eth_wht', None, 'cast({src_column} as bool)'),
        ('3', 'stg_sbac_asmt_outcome', 'DemographicRaceTwoOrMoreRaces', 'int_sbac_asmt_outcome', 'dmg_eth_2om', None, 'cast({src_column} as bool)'),
        ('3', 'stg_sbac_asmt_outcome', 'IDEAIndicator', 'int_sbac_asmt_outcome', 'dmg_prg_iep', None, 'cast({src_column} as bool)'),
        ('3', 'stg_sbac_asmt_outcome', 'LEPStatus', 'int_sbac_asmt_outcome', 'dmg_prg_lep', None, 'cast({src_column} as bool)'),
        ('3', 'stg_sbac_asmt_outcome', 'Section504Status', 'int_sbac_asmt_outcome', 'dmg_prg_504', None, 'cast({src_column} as bool)'),
        ('3', 'stg_sbac_asmt_outcome', 'EconomicDisadvantageStatus', 'int_sbac_asmt_outcome', 'dmg_sts_ecd', None, 'cast({src_column} as bool)'),
        ('3', 'stg_sbac_asmt_outcome', 'MigrantStatus', 'int_sbac_asmt_outcome', 'dmg_sts_mig', None, 'cast({src_column} as bool)'),
        ('3', 'stg_sbac_asmt_outcome', "BlackOrAfricanAmerican, Asian, HispanicOrLatinoEthnicity, AmericanIndianOrAlaskaNative, NativeHawaiianOrOtherPacificIslander, White, DemographicRaceTwoOrMoreRaces", 'int_sbac_asmt_outcome', 'dmg_eth_derived', 'deriveEthnicity', None),
        ('3', 'stg_sbac_asmt_outcome', 'HispanicOrLatinoEthnicity', 'int_sbac_asmt_outcome', 'dmg_eth_hsp', None, 'cast({src_column} as bool)'),
        ('3', 'stg_sbac_asmt_outcome', 'AmericanIndianOrAlaskaNative', 'int_sbac_asmt_outcome', 'dmg_eth_ami', None, 'cast({src_column} as bool)'),
        ('3', 'stg_sbac_asmt_outcome', 'Asian', 'int_sbac_asmt_outcome', 'dmg_eth_asn', None, 'cast({src_column} as bool)'),
        ('3', 'stg_sbac_asmt_outcome', 'BlackOrAfricanAmerican', 'int_sbac_asmt_outcome', 'dmg_eth_blk', None, 'cast({src_column} as bool)'),
        ('3', 'stg_sbac_asmt_outcome', 'NativeHawaiianOrOtherPacificIslander', 'int_sbac_asmt_outcome', 'dmg_eth_pcf', None, 'cast({src_column} as bool)'),
        ('3', 'stg_sbac_asmt_outcome', 'White', 'int_sbac_asmt_outcome', 'dmg_eth_wht', None, 'cast({src_column} as bool)'),
        ('3', 'stg_sbac_asmt_outcome', 'DemographicRaceTwoOrMoreRaces', 'int_sbac_asmt_outcome', 'dmg_eth_2om', None, 'cast({src_column} as bool)'),
        ('3', 'stg_sbac_asmt_outcome', 'IDEAIndicator', 'int_sbac_asmt_outcome', 'dmg_prg_iep', None, 'cast({src_column} as bool)'),
        ('3', 'stg_sbac_asmt_outcome', 'LEPStatus', 'int_sbac_asmt_outcome', 'dmg_prg_lep', None, 'cast({src_column} as bool)'),
        ('3', 'stg_sbac_asmt_outcome', 'Section504Status', 'int_sbac_asmt_outcome', 'dmg_prg_504', None, 'cast({src_column} as bool)'),
        ('3', 'stg_sbac_asmt_outcome', 'EconomicDisadvantageStatus', 'int_sbac_asmt_outcome', 'dmg_sts_ecd', None, 'cast({src_column} as bool)'),
        ('3', 'stg_sbac_asmt_outcome', 'MigrantStatus', 'int_sbac_asmt_outcome', 'dmg_sts_mig', None, 'cast({src_column} as bool)'),
        ('3', 'stg_sbac_asmt_outcome', 'Group1Id', 'int_sbac_asmt_outcome', 'group_1_id', None, 'substr({src_column}, 1, {length})'),
        ('3', 'stg_sbac_asmt_outcome', 'Group1Text', 'int_sbac_asmt_outcome', 'group_1_text', None, 'substr({src_column}, 1, {length})'),
        ('3', 'stg_sbac_asmt_outcome', 'Group2Id', 'int_sbac_asmt_outcome', 'group_2_id', None, 'substr({src_column}, 1, {length})'),
        ('3', 'stg_sbac_asmt_outcome', 'Group2Text', 'int_sbac_asmt_outcome', 'group_2_text', None, 'substr({src_column}, 1, {length})'),
        ('3', 'stg_sbac_asmt_outcome', 'AssessmentGuid', 'int_sbac_asmt_outcome', 'guid_asmt', None, 'substr({src_column}, 1, {length})'),
        ('3', 'stg_sbac_asmt_outcome', 'AssessmentSessionLocationId', 'int_sbac_asmt_outcome', 'guid_asmt_location', None, 'substr({src_column}, 1, {length})'),
        ('3', 'stg_sbac_asmt_outcome', 'AssessmentSessionLocation', 'int_sbac_asmt_outcome', 'name_asmt_location', None, 'substr({src_column}, 1, {length})'),
        ('3', 'stg_sbac_asmt_outcome', 'AssessmentAdministrationFinishDate', 'int_sbac_asmt_outcome', 'date_assessed', None, 'substr({src_column}, 1, {length})'),
        ('3', 'stg_sbac_asmt_outcome', 'AssessmentAdministrationFinishDate', 'int_sbac_asmt_outcome', 'date_taken_day', None, "extract(day from to_date({src_column}, 'YYYYMMDD'))"),
        ('3', 'stg_sbac_asmt_outcome', 'AssessmentAdministrationFinishDate', 'int_sbac_asmt_outcome', 'date_taken_month', None, "extract(month from to_date({src_column}, 'YYYYMMDD'))"),
        ('3', 'stg_sbac_asmt_outcome', 'AssessmentAdministrationFinishDate', 'int_sbac_asmt_outcome', 'date_taken_year', None, "extract(year from to_date({src_column}, 'YYYYMMDD'))"),
        ('3', 'stg_sbac_asmt_outcome', 'AssessmentYear', 'int_sbac_asmt_outcome', 'asmt_year', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AssessmentType', 'int_sbac_asmt_outcome', 'asmt_type', None, 'substr({src_column}, 1, {length})'),
        ('3', 'stg_sbac_asmt_outcome', 'AssessmentAcademicSubject', 'int_sbac_asmt_outcome', 'asmt_subject', None, 'substr({src_column}, 1, {length})'),
        ('3', 'stg_sbac_asmt_outcome', 'AssessmentLevelForWhichDesigned', 'int_sbac_asmt_outcome', 'grade_asmt', None, 'substr({src_column}, 1, {length})'),
        ('3', 'stg_sbac_asmt_outcome', 'AssessmentSubtestResultScoreValue', 'int_sbac_asmt_outcome', 'score_asmt', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AssessmentSubtestMinimumValue', 'int_sbac_asmt_outcome', 'score_asmt_min', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AssessmentSubtestMaximumValue', 'int_sbac_asmt_outcome', 'score_asmt_max', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AssessmentPerformanceLevelIdentifier', 'int_sbac_asmt_outcome', 'score_perf_level', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AssessmentSubtestResultScoreClaim1Value', 'int_sbac_asmt_outcome', 'score_claim_1', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AssessmentSubtestClaim1MinimumValue', 'int_sbac_asmt_outcome', 'score_claim_1_min', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AssessmentSubtestClaim1MaximumValue', 'int_sbac_asmt_outcome', 'score_claim_1_max', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AssessmentSubtestClaim1PerformanceLevelIdentifier', 'int_sbac_asmt_outcome', 'asmt_claim_1_perf_lvl', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AssessmentSubtestResultScoreClaim2Value', 'int_sbac_asmt_outcome', 'score_claim_2', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AssessmentSubtestClaim2MinimumValue', 'int_sbac_asmt_outcome', 'score_claim_2_min', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AssessmentSubtestClaim2MaximumValue', 'int_sbac_asmt_outcome', 'score_claim_2_max', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AssessmentSubtestClaim2PerformanceLevelIdentifier', 'int_sbac_asmt_outcome', 'asmt_claim_2_perf_lvl', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AssessmentSubtestResultScoreClaim3Value', 'int_sbac_asmt_outcome', 'score_claim_3', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AssessmentSubtestClaim3MinimumValue', 'int_sbac_asmt_outcome', 'score_claim_3_min', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AssessmentSubtestClaim3MaximumValue', 'int_sbac_asmt_outcome', 'score_claim_3_max', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AssessmentSubtestClaim3PerformanceLevelIdentifier', 'int_sbac_asmt_outcome', 'asmt_claim_3_perf_lvl', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AssessmentSubtestResultScoreClaim4Value', 'int_sbac_asmt_outcome', 'score_claim_4', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AssessmentSubtestClaim4MinimumValue', 'int_sbac_asmt_outcome', 'score_claim_4_min', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AssessmentSubtestClaim4MaximumValue', 'int_sbac_asmt_outcome', 'score_claim_4_max', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AssessmentSubtestClaim4PerformanceLevelIdentifier', 'int_sbac_asmt_outcome', 'asmt_claim_4_perf_lvl', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'created_date', 'int_sbac_asmt_outcome', 'created_date', None, None),
        ('3', 'stg_sbac_asmt_outcome', 'AccommodationAmericanSignLanguage', 'int_sbac_asmt_outcome', 'acc_asl_video_embed', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AccommodationSignLanguageHumanIntervention', 'int_sbac_asmt_outcome', 'acc_asl_human_nonembed', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AccommodationBraille', 'int_sbac_asmt_outcome', 'acc_braile_embed', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AccommodationClosedCaptioning', 'int_sbac_asmt_outcome', 'acc_closed_captioning_embed', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AccommodationTextToSpeech', 'int_sbac_asmt_outcome', 'acc_text_to_speech_embed', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AccommodationAbacus', 'int_sbac_asmt_outcome', 'acc_abacus_nonembed', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AccommodationAlternateResponseOptions', 'int_sbac_asmt_outcome', 'acc_alternate_response_options_nonembed', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AccommodationCalculator', 'int_sbac_asmt_outcome', 'acc_calculator_nonembed', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AccommodationMultiplicationTable', 'int_sbac_asmt_outcome', 'acc_multiplication_table_nonembed', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AccommodationPrintOnDemand', 'int_sbac_asmt_outcome', 'acc_print_on_demand_nonembed', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AccommodationReadAloud', 'int_sbac_asmt_outcome', 'acc_read_aloud_nonembed', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AccommodationScribe', 'int_sbac_asmt_outcome', 'acc_scribe_nonembed', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AccommodationSpeechToText', 'int_sbac_asmt_outcome', 'acc_speech_to_text_nonembed', None, "to_number({src_column}, '99999')"),
        ('3', 'stg_sbac_asmt_outcome', 'AccommodationStreamlineMode', 'int_sbac_asmt_outcome', 'acc_streamline_mode', None, "to_number({src_column}, '99999')"),
        # Integration to Target
        ('4', 'int_sbac_asmt', 'record_sid', 'dim_asmt', 'asmt_rec_id', None, None),
        ('4', 'int_sbac_asmt', 'guid_asmt', 'dim_asmt', 'asmt_guid', None, None),
        ('4', 'int_sbac_asmt', 'type', 'dim_asmt', 'asmt_type', None, None),
        ('4', 'int_sbac_asmt', 'period', 'dim_asmt', 'asmt_period', None, None),
        ('4', 'int_sbac_asmt', 'year', 'dim_asmt', 'asmt_period_year', None, None),
        ('4', 'int_sbac_asmt', 'version', 'dim_asmt', 'asmt_version', None, None),
        ('4', 'int_sbac_asmt', 'subject', 'dim_asmt', 'asmt_subject', None, None),
        ('4', 'int_sbac_asmt', 'name_claim_1', 'dim_asmt', 'asmt_claim_1_name', None, None),
        ('4', 'int_sbac_asmt', 'name_claim_2', 'dim_asmt', 'asmt_claim_2_name', None, None),
        ('4', 'int_sbac_asmt', 'name_claim_3', 'dim_asmt', 'asmt_claim_3_name', None, None),
        ('4', 'int_sbac_asmt', 'name_claim_4', 'dim_asmt', 'asmt_claim_4_name', None, None),
        ('4', 'int_sbac_asmt', 'name_perf_lvl_1', 'dim_asmt', 'asmt_perf_lvl_name_1', None, None),
        ('4', 'int_sbac_asmt', 'name_perf_lvl_2', 'dim_asmt', 'asmt_perf_lvl_name_2', None, None),
        ('4', 'int_sbac_asmt', 'name_perf_lvl_3', 'dim_asmt', 'asmt_perf_lvl_name_3', None, None),
        ('4', 'int_sbac_asmt', 'name_perf_lvl_4', 'dim_asmt', 'asmt_perf_lvl_name_4', None, None),
        ('4', 'int_sbac_asmt', 'name_perf_lvl_5', 'dim_asmt', 'asmt_perf_lvl_name_5', None, None),
        ('4', 'int_sbac_asmt', 'asmt_claim_perf_lvl_name_1', 'dim_asmt', 'asmt_claim_perf_lvl_name_1', None, None),
        ('4', 'int_sbac_asmt', 'asmt_claim_perf_lvl_name_2', 'dim_asmt', 'asmt_claim_perf_lvl_name_2', None, None),
        ('4', 'int_sbac_asmt', 'asmt_claim_perf_lvl_name_3', 'dim_asmt', 'asmt_claim_perf_lvl_name_3', None, None),
        ('4', 'int_sbac_asmt', 'score_overall_min', 'dim_asmt', 'asmt_score_min', None, None),
        ('4', 'int_sbac_asmt', 'score_overall_max', 'dim_asmt', 'asmt_score_max', None, None),
        ('4', 'int_sbac_asmt', 'score_claim_1_min', 'dim_asmt', 'asmt_claim_1_score_min', None, None),
        ('4', 'int_sbac_asmt', 'score_claim_1_max', 'dim_asmt', 'asmt_claim_1_score_max', None, None),
        ('4', 'int_sbac_asmt', 'score_claim_2_min', 'dim_asmt', 'asmt_claim_2_score_min', None, None),
        ('4', 'int_sbac_asmt', 'score_claim_2_max', 'dim_asmt', 'asmt_claim_2_score_max', None, None),
        ('4', 'int_sbac_asmt', 'score_claim_3_min', 'dim_asmt', 'asmt_claim_3_score_min', None, None),
        ('4', 'int_sbac_asmt', 'score_claim_3_max', 'dim_asmt', 'asmt_claim_3_score_max', None, None),
        ('4', 'int_sbac_asmt', 'score_claim_4_min', 'dim_asmt', 'asmt_claim_4_score_min', None, None),
        ('4', 'int_sbac_asmt', 'score_claim_4_max', 'dim_asmt', 'asmt_claim_4_score_max', None, None),
        ('4', 'int_sbac_asmt', 'score_cut_point_1', 'dim_asmt', 'asmt_cut_point_1', None, None),
        ('4', 'int_sbac_asmt', 'score_cut_point_2', 'dim_asmt', 'asmt_cut_point_2', None, None),
        ('4', 'int_sbac_asmt', 'score_cut_point_3', 'dim_asmt', 'asmt_cut_point_3', None, None),
        ('4', 'int_sbac_asmt', 'score_cut_point_4', 'dim_asmt', 'asmt_cut_point_4', None, None),
        ('4', 'int_sbac_asmt', 'effective_date', 'dim_asmt', 'effective_date', None, None),
        ('4', 'int_sbac_asmt', "TO_CHAR(CURRENT_TIMESTAMP, 'yyyymmdd')", 'dim_asmt', 'from_date', None, None),
        ('4', 'int_sbac_asmt', "'99991231'", 'dim_asmt', 'to_date', None, None),
        ('4', 'int_sbac_asmt', "'C'", 'dim_asmt', 'rec_status', None, None),
        ('4', 'int_sbac_asmt', 'guid_batch', 'dim_asmt', 'batch_guid', None, None),
        ('4', 'int_sbac_asmt_outcome', 'record_sid', 'dim_inst_hier', 'inst_hier_rec_id', None, None),
        ('4', 'int_sbac_asmt_outcome', 'code_state', 'dim_inst_hier', 'state_code', None, None),
        ('4', 'int_sbac_asmt_outcome', 'guid_district', 'dim_inst_hier', 'district_id', None, None),
        ('4', 'int_sbac_asmt_outcome', 'name_district', 'dim_inst_hier', 'district_name', None, None),
        ('4', 'int_sbac_asmt_outcome', 'guid_school', 'dim_inst_hier', 'school_id', None, None),
        ('4', 'int_sbac_asmt_outcome', 'name_school', 'dim_inst_hier', 'school_name', None, None),
        ('4', 'int_sbac_asmt_outcome', "to_char(CURRENT_TIMESTAMP, 'yyyymmdd')", 'dim_inst_hier', 'from_date', None, None),
        ('4', 'int_sbac_asmt_outcome', "'99991231'", 'dim_inst_hier', 'to_date', None, None),
        ('4', 'int_sbac_asmt_outcome', 'op', 'dim_inst_hier', 'rec_status', None, None),
        ('4', 'int_sbac_asmt_outcome', 'guid_batch', 'dim_inst_hier', 'batch_guid', None, None),
        ('4', 'int_sbac_asmt_outcome', 'record_sid', 'dim_student', 'student_rec_id', None, None),
        ('4', 'int_sbac_asmt_outcome', 'guid_student', 'dim_student', 'student_id', None, None),
        ('4', 'int_sbac_asmt_outcome', 'external_student_id', 'dim_student', 'external_student_id', None, None),
        ('4', 'int_sbac_asmt_outcome', 'name_student_first', 'dim_student', 'first_name', None, None),
        ('4', 'int_sbac_asmt_outcome', 'name_student_middle', 'dim_student', 'middle_name', None, None),
        ('4', 'int_sbac_asmt_outcome', 'name_student_last', 'dim_student', 'last_name', None, None),
        ('4', 'int_sbac_asmt_outcome', 'birthdate_student', 'dim_student', 'birthdate', None, None),
        ('4', 'int_sbac_asmt_outcome', 'sex_student', 'dim_student', 'sex', None, None),
        ('4', 'int_sbac_asmt_outcome', 'dmg_eth_derived', 'dim_student', 'dmg_eth_derived', None, None),
        ('4', 'int_sbac_asmt_outcome', 'dmg_eth_hsp', 'dim_student', 'dmg_eth_hsp', None, None),
        ('4', 'int_sbac_asmt_outcome', 'dmg_eth_ami', 'dim_student', 'dmg_eth_ami', None, None),
        ('4', 'int_sbac_asmt_outcome', 'dmg_eth_asn', 'dim_student', 'dmg_eth_asn', None, None),
        ('4', 'int_sbac_asmt_outcome', 'dmg_eth_blk', 'dim_student', 'dmg_eth_blk', None, None),
        ('4', 'int_sbac_asmt_outcome', 'dmg_eth_pcf', 'dim_student', 'dmg_eth_pcf', None, None),
        ('4', 'int_sbac_asmt_outcome', 'dmg_eth_wht', 'dim_student', 'dmg_eth_wht', None, None),
        ('4', 'int_sbac_asmt_outcome', 'dmg_eth_2om', 'dim_student', 'dmg_eth_2om', None, None),
        ('4', 'int_sbac_asmt_outcome', 'dmg_prg_iep', 'dim_student', 'dmg_prg_iep', None, None),
        ('4', 'int_sbac_asmt_outcome', 'dmg_prg_lep', 'dim_student', 'dmg_prg_lep', None, None),
        ('4', 'int_sbac_asmt_outcome', 'dmg_prg_504', 'dim_student', 'dmg_prg_504', None, None),
        ('4', 'int_sbac_asmt_outcome', 'dmg_sts_ecd', 'dim_student', 'dmg_sts_ecd', None, None),
        ('4', 'int_sbac_asmt_outcome', 'dmg_sts_mig', 'dim_student', 'dmg_sts_mig', None, None),
        ('4', 'int_sbac_asmt_outcome', "to_char(CURRENT_TIMESTAMP,'yyyymmdd')", 'dim_student', 'from_date', None, None),
        ('4', 'int_sbac_asmt_outcome', "'99991231'", 'dim_student', 'to_date', None, None),
        ('4', 'int_sbac_asmt_outcome', 'op', 'dim_student', 'rec_status', None, None),
        ('4', 'int_sbac_asmt_outcome', 'guid_batch', 'dim_student', 'batch_guid', None, None),
        ('4', 'int_sbac_asmt_outcome', 'record_sid', 'fact_asmt_outcome_vw', 'asmt_outcome_vw_rec_id', None, None),
        ('4', 'int_sbac_asmt_outcome', '-1', 'fact_asmt_outcome_vw', 'asmt_rec_id', None, None),
        ('4', 'int_sbac_asmt_outcome', '-1', 'fact_asmt_outcome_vw', 'student_rec_id', None, None),
        ('4', 'int_sbac_asmt_outcome', '-1', 'fact_asmt_outcome_vw', 'inst_hier_rec_id', None, None),
        ('4', 'int_sbac_asmt_outcome', 'guid_asmt', 'fact_asmt_outcome_vw', 'asmt_guid', None, None),
        ('4', 'int_sbac_asmt_outcome', 'guid_student', 'fact_asmt_outcome_vw', 'student_id', None, None),
        ('4', 'int_sbac_asmt_outcome', 'code_state', 'fact_asmt_outcome_vw', 'state_code', None, None),
        ('4', 'int_sbac_asmt_outcome', 'guid_district', 'fact_asmt_outcome_vw', 'district_id', None, None),
        ('4', 'int_sbac_asmt_outcome', 'guid_school', 'fact_asmt_outcome_vw', 'school_id', None, None),
        ('4', 'int_sbac_asmt_outcome', 'guid_asmt_location', 'fact_asmt_outcome_vw', 'where_taken_id', None, None),
        ('4', 'int_sbac_asmt_outcome', 'name_asmt_location', 'fact_asmt_outcome_vw', 'where_taken_name', None, None),
        ('4', 'int_sbac_asmt_outcome', 'grade_asmt', 'fact_asmt_outcome_vw', 'asmt_grade', None, None),
        ('4', 'int_sbac_asmt_outcome', 'grade_enrolled', 'fact_asmt_outcome_vw', 'enrl_grade', None, None),
        ('4', 'int_sbac_asmt_outcome', 'group_1_id', 'fact_asmt_outcome_vw', 'group_1_id', None, None),
        ('4', 'int_sbac_asmt_outcome', 'group_1_text', 'fact_asmt_outcome_vw', 'group_1_text', None, None),
        ('4', 'int_sbac_asmt_outcome', 'group_2_id', 'fact_asmt_outcome_vw', 'group_2_id', None, None),
        ('4', 'int_sbac_asmt_outcome', 'group_2_text', 'fact_asmt_outcome_vw', 'group_2_text', None, None),
        ('4', 'int_sbac_asmt_outcome', 'date_assessed', 'fact_asmt_outcome_vw', 'date_taken', None, None),
        ('4', 'int_sbac_asmt_outcome', 'date_taken_day', 'fact_asmt_outcome_vw', 'date_taken_day', None, None),
        ('4', 'int_sbac_asmt_outcome', 'date_taken_month', 'fact_asmt_outcome_vw', 'date_taken_month', None, None),
        ('4', 'int_sbac_asmt_outcome', 'date_taken_year', 'fact_asmt_outcome_vw', 'date_taken_year', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_asmt', 'fact_asmt_outcome_vw', 'asmt_score', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_asmt_min', 'fact_asmt_outcome_vw', 'asmt_score_range_min', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_asmt_max', 'fact_asmt_outcome_vw', 'asmt_score_range_max', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_perf_level', 'fact_asmt_outcome_vw', 'asmt_perf_lvl', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_claim_1', 'fact_asmt_outcome_vw', 'asmt_claim_1_score', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_claim_1_min', 'fact_asmt_outcome_vw', 'asmt_claim_1_score_range_min', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_claim_1_max', 'fact_asmt_outcome_vw', 'asmt_claim_1_score_range_max', None, None),
        ('4', 'int_sbac_asmt_outcome', 'asmt_claim_1_perf_lvl', 'fact_asmt_outcome_vw', 'asmt_claim_1_perf_lvl', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_claim_2', 'fact_asmt_outcome_vw', 'asmt_claim_2_score', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_claim_2_min', 'fact_asmt_outcome_vw', 'asmt_claim_2_score_range_min', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_claim_2_max', 'fact_asmt_outcome_vw', 'asmt_claim_2_score_range_max', None, None),
        ('4', 'int_sbac_asmt_outcome', 'asmt_claim_2_perf_lvl', 'fact_asmt_outcome_vw', 'asmt_claim_2_perf_lvl', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_claim_3', 'fact_asmt_outcome_vw', 'asmt_claim_3_score', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_claim_3_min', 'fact_asmt_outcome_vw', 'asmt_claim_3_score_range_min', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_claim_3_max', 'fact_asmt_outcome_vw', 'asmt_claim_3_score_range_max', None, None),
        ('4', 'int_sbac_asmt_outcome', 'asmt_claim_3_perf_lvl', 'fact_asmt_outcome_vw', 'asmt_claim_3_perf_lvl', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_claim_4', 'fact_asmt_outcome_vw', 'asmt_claim_4_score', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_claim_4_min', 'fact_asmt_outcome_vw', 'asmt_claim_4_score_range_min', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_claim_4_max', 'fact_asmt_outcome_vw', 'asmt_claim_4_score_range_max', None, None),
        ('4', 'int_sbac_asmt_outcome', 'asmt_claim_4_perf_lvl', 'fact_asmt_outcome_vw', 'asmt_claim_4_perf_lvl', None, None),
        ('4', 'int_sbac_asmt_outcome', 'asmt_type', 'fact_asmt_outcome_vw', 'asmt_type', None, None),
        ('4', 'int_sbac_asmt_outcome', 'asmt_subject', 'fact_asmt_outcome_vw', 'asmt_subject', None, None),
        ('4', 'int_sbac_asmt_outcome', 'asmt_year', 'fact_asmt_outcome_vw', 'asmt_year', None, None),
        ('4', 'int_sbac_asmt_outcome', 'sex_student', 'fact_asmt_outcome_vw', 'sex', None, None),
        ('4', 'int_sbac_asmt_outcome', 'dmg_eth_derived', 'fact_asmt_outcome_vw', 'dmg_eth_derived', None, None),
        ('4', 'int_sbac_asmt_outcome', 'dmg_eth_hsp', 'fact_asmt_outcome_vw', 'dmg_eth_hsp', None, None),
        ('4', 'int_sbac_asmt_outcome', 'dmg_eth_ami', 'fact_asmt_outcome_vw', 'dmg_eth_ami', None, None),
        ('4', 'int_sbac_asmt_outcome', 'dmg_eth_asn', 'fact_asmt_outcome_vw', 'dmg_eth_asn', None, None),
        ('4', 'int_sbac_asmt_outcome', 'dmg_eth_blk', 'fact_asmt_outcome_vw', 'dmg_eth_blk', None, None),
        ('4', 'int_sbac_asmt_outcome', 'dmg_eth_pcf', 'fact_asmt_outcome_vw', 'dmg_eth_pcf', None, None),
        ('4', 'int_sbac_asmt_outcome', 'dmg_eth_wht', 'fact_asmt_outcome_vw', 'dmg_eth_wht', None, None),
        ('4', 'int_sbac_asmt_outcome', 'dmg_eth_2om', 'fact_asmt_outcome_vw', 'dmg_eth_2om', None, None),
        ('4', 'int_sbac_asmt_outcome', 'dmg_prg_iep', 'fact_asmt_outcome_vw', 'dmg_prg_iep', None, None),
        ('4', 'int_sbac_asmt_outcome', 'dmg_prg_lep', 'fact_asmt_outcome_vw', 'dmg_prg_lep', None, None),
        ('4', 'int_sbac_asmt_outcome', 'dmg_prg_504', 'fact_asmt_outcome_vw', 'dmg_prg_504', None, None),
        ('4', 'int_sbac_asmt_outcome', 'dmg_sts_ecd', 'fact_asmt_outcome_vw', 'dmg_sts_ecd', None, None),
        ('4', 'int_sbac_asmt_outcome', 'dmg_sts_mig', 'fact_asmt_outcome_vw', 'dmg_sts_mig', None, None),
        ('4', 'int_sbac_asmt_outcome', 'acc_asl_video_embed', 'fact_asmt_outcome_vw', 'acc_asl_video_embed', None, None),
        ('4', 'int_sbac_asmt_outcome', 'acc_asl_human_nonembed', 'fact_asmt_outcome_vw', 'acc_asl_human_nonembed', None, None),
        ('4', 'int_sbac_asmt_outcome', 'acc_braile_embed', 'fact_asmt_outcome_vw', 'acc_braile_embed', None, None),
        ('4', 'int_sbac_asmt_outcome', 'acc_closed_captioning_embed', 'fact_asmt_outcome_vw', 'acc_closed_captioning_embed', None, None),
        ('4', 'int_sbac_asmt_outcome', 'acc_text_to_speech_embed', 'fact_asmt_outcome_vw', 'acc_text_to_speech_embed', None, None),
        ('4', 'int_sbac_asmt_outcome', 'acc_abacus_nonembed', 'fact_asmt_outcome_vw', 'acc_abacus_nonembed', None, None),
        ('4', 'int_sbac_asmt_outcome', 'acc_alternate_response_options_nonembed', 'fact_asmt_outcome_vw', 'acc_alternate_response_options_nonembed', None, None),
        ('4', 'int_sbac_asmt_outcome', 'acc_calculator_nonembed', 'fact_asmt_outcome_vw', 'acc_calculator_nonembed', None, None),
        ('4', 'int_sbac_asmt_outcome', 'acc_multiplication_table_nonembed', 'fact_asmt_outcome_vw', 'acc_multiplication_table_nonembed', None, None),
        ('4', 'int_sbac_asmt_outcome', 'acc_print_on_demand_nonembed', 'fact_asmt_outcome_vw', 'acc_print_on_demand_nonembed', None, None),
        ('4', 'int_sbac_asmt_outcome', 'acc_read_aloud_nonembed', 'fact_asmt_outcome_vw', 'acc_read_aloud_nonembed', None, None),
        ('4', 'int_sbac_asmt_outcome', 'acc_scribe_nonembed', 'fact_asmt_outcome_vw', 'acc_scribe_nonembed', None, None),
        ('4', 'int_sbac_asmt_outcome', 'acc_speech_to_text_nonembed', 'fact_asmt_outcome_vw', 'acc_speech_to_text_nonembed', None, None),
        ('4', 'int_sbac_asmt_outcome', 'acc_streamline_mode', 'fact_asmt_outcome_vw', 'acc_streamline_mode', None, None),
        ('4', 'int_sbac_asmt_outcome', "TO_CHAR(CURRENT_TIMESTAMP, 'yyyymmdd')", 'fact_asmt_outcome_vw', 'from_date', None, None),
        ('4', 'int_sbac_asmt_outcome', "'99991231'", 'fact_asmt_outcome_vw', 'to_date', None, None),
        ('4', 'int_sbac_asmt_outcome', 'op', 'fact_asmt_outcome_vw', 'rec_status', None, None),
        ('4', 'int_sbac_asmt_outcome', 'guid_batch', 'fact_asmt_outcome_vw', 'batch_guid', None, None),
        ('4', 'int_sbac_asmt_outcome', 'record_sid', 'fact_asmt_outcome', 'asmt_outcome_rec_id', None, None),
        ('4', 'int_sbac_asmt_outcome', '-1', 'fact_asmt_outcome', 'asmt_rec_id', None, None),
        ('4', 'int_sbac_asmt_outcome', '-1', 'fact_asmt_outcome', 'student_rec_id', None, None),
        ('4', 'int_sbac_asmt_outcome', '-1', 'fact_asmt_outcome', 'inst_hier_rec_id', None, None),
        ('4', 'int_sbac_asmt_outcome', 'guid_asmt', 'fact_asmt_outcome', 'asmt_guid', None, None),
        ('4', 'int_sbac_asmt_outcome', 'guid_student', 'fact_asmt_outcome', 'student_id', None, None),
        ('4', 'int_sbac_asmt_outcome', 'code_state', 'fact_asmt_outcome', 'state_code', None, None),
        ('4', 'int_sbac_asmt_outcome', 'guid_district', 'fact_asmt_outcome', 'district_id', None, None),
        ('4', 'int_sbac_asmt_outcome', 'guid_school', 'fact_asmt_outcome', 'school_id', None, None),
        ('4', 'int_sbac_asmt_outcome', 'guid_asmt_location', 'fact_asmt_outcome', 'where_taken_id', None, None),
        ('4', 'int_sbac_asmt_outcome', 'name_asmt_location', 'fact_asmt_outcome', 'where_taken_name', None, None),
        ('4', 'int_sbac_asmt_outcome', 'grade_asmt', 'fact_asmt_outcome', 'asmt_grade', None, None),
        ('4', 'int_sbac_asmt_outcome', 'grade_enrolled', 'fact_asmt_outcome', 'enrl_grade', None, None),
        ('4', 'int_sbac_asmt_outcome', 'group_1_id', 'fact_asmt_outcome', 'group_1_id', None, None),
        ('4', 'int_sbac_asmt_outcome', 'group_1_text', 'fact_asmt_outcome', 'group_1_text', None, None),
        ('4', 'int_sbac_asmt_outcome', 'group_2_id', 'fact_asmt_outcome', 'group_2_id', None, None),
        ('4', 'int_sbac_asmt_outcome', 'group_2_text', 'fact_asmt_outcome', 'group_2_text', None, None),
        ('4', 'int_sbac_asmt_outcome', 'date_assessed', 'fact_asmt_outcome', 'date_taken', None, None),
        ('4', 'int_sbac_asmt_outcome', 'date_taken_day', 'fact_asmt_outcome', 'date_taken_day', None, None),
        ('4', 'int_sbac_asmt_outcome', 'date_taken_month', 'fact_asmt_outcome', 'date_taken_month', None, None),
        ('4', 'int_sbac_asmt_outcome', 'date_taken_year', 'fact_asmt_outcome', 'date_taken_year', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_asmt', 'fact_asmt_outcome', 'asmt_score', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_asmt_min', 'fact_asmt_outcome', 'asmt_score_range_min', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_asmt_max', 'fact_asmt_outcome', 'asmt_score_range_max', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_perf_level', 'fact_asmt_outcome', 'asmt_perf_lvl', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_claim_1', 'fact_asmt_outcome', 'asmt_claim_1_score', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_claim_1_min', 'fact_asmt_outcome', 'asmt_claim_1_score_range_min', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_claim_1_max', 'fact_asmt_outcome', 'asmt_claim_1_score_range_max', None, None),
        ('4', 'int_sbac_asmt_outcome', 'asmt_claim_1_perf_lvl', 'fact_asmt_outcome', 'asmt_claim_1_perf_lvl', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_claim_2', 'fact_asmt_outcome', 'asmt_claim_2_score', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_claim_2_min', 'fact_asmt_outcome', 'asmt_claim_2_score_range_min', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_claim_2_max', 'fact_asmt_outcome', 'asmt_claim_2_score_range_max', None, None),
        ('4', 'int_sbac_asmt_outcome', 'asmt_claim_2_perf_lvl', 'fact_asmt_outcome', 'asmt_claim_2_perf_lvl', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_claim_3', 'fact_asmt_outcome', 'asmt_claim_3_score', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_claim_3_min', 'fact_asmt_outcome', 'asmt_claim_3_score_range_min', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_claim_3_max', 'fact_asmt_outcome', 'asmt_claim_3_score_range_max', None, None),
        ('4', 'int_sbac_asmt_outcome', 'asmt_claim_3_perf_lvl', 'fact_asmt_outcome', 'asmt_claim_3_perf_lvl', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_claim_4', 'fact_asmt_outcome', 'asmt_claim_4_score', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_claim_4_min', 'fact_asmt_outcome', 'asmt_claim_4_score_range_min', None, None),
        ('4', 'int_sbac_asmt_outcome', 'score_claim_4_max', 'fact_asmt_outcome', 'asmt_claim_4_score_range_max', None, None),
        ('4', 'int_sbac_asmt_outcome', 'asmt_claim_4_perf_lvl', 'fact_asmt_outcome', 'asmt_claim_4_perf_lvl', None, None),
        ('4', 'int_sbac_asmt_outcome', 'acc_asl_video_embed', 'fact_asmt_outcome', 'acc_asl_video_embed', None, None),
        ('4', 'int_sbac_asmt_outcome', 'acc_asl_human_nonembed', 'fact_asmt_outcome', 'acc_asl_human_nonembed', None, None),
        ('4', 'int_sbac_asmt_outcome', 'acc_braile_embed', 'fact_asmt_outcome', 'acc_braile_embed', None, None),
        ('4', 'int_sbac_asmt_outcome', 'acc_closed_captioning_embed', 'fact_asmt_outcome', 'acc_closed_captioning_embed', None, None),
        ('4', 'int_sbac_asmt_outcome', 'acc_text_to_speech_embed', 'fact_asmt_outcome', 'acc_text_to_speech_embed', None, None),
        ('4', 'int_sbac_asmt_outcome', 'acc_abacus_nonembed', 'fact_asmt_outcome', 'acc_abacus_nonembed', None, None),
        ('4', 'int_sbac_asmt_outcome', 'acc_alternate_response_options_nonembed', 'fact_asmt_outcome', 'acc_alternate_response_options_nonembed', None, None),
        ('4', 'int_sbac_asmt_outcome', 'acc_calculator_nonembed', 'fact_asmt_outcome', 'acc_calculator_nonembed', None, None),
        ('4', 'int_sbac_asmt_outcome', 'acc_multiplication_table_nonembed', 'fact_asmt_outcome', 'acc_multiplication_table_nonembed', None, None),
        ('4', 'int_sbac_asmt_outcome', 'acc_print_on_demand_nonembed', 'fact_asmt_outcome', 'acc_print_on_demand_nonembed', None, None),
        ('4', 'int_sbac_asmt_outcome', 'acc_read_aloud_nonembed', 'fact_asmt_outcome', 'acc_read_aloud_nonembed', None, None),
        ('4', 'int_sbac_asmt_outcome', 'acc_scribe_nonembed', 'fact_asmt_outcome', 'acc_scribe_nonembed', None, None),
        ('4', 'int_sbac_asmt_outcome', 'acc_speech_to_text_nonembed', 'fact_asmt_outcome', 'acc_speech_to_text_nonembed', None, None),
        ('4', 'int_sbac_asmt_outcome', 'acc_streamline_mode', 'fact_asmt_outcome', 'acc_streamline_mode', None, None),
        ('4', 'int_sbac_asmt_outcome', "TO_CHAR(CURRENT_TIMESTAMP, 'yyyymmdd')", 'fact_asmt_outcome', 'from_date', None, None),
        ('4', 'int_sbac_asmt_outcome', "'99991231'", 'fact_asmt_outcome', 'to_date', None, None),
        ('4', 'int_sbac_asmt_outcome', 'op', 'fact_asmt_outcome', 'rec_status', None, None),
        ('4', 'int_sbac_asmt_outcome', 'guid_batch', 'fact_asmt_outcome', 'batch_guid', None, None),
        # Used only in reporting app, smarter.  udl should never pick this up
        ('1000', 'int_sbac_asmt_outcome', 'guid_asmt', 'dim_asmt', 'asmt_guid', None, None),
    ]
}
