from config import ref_table_data as ref_constants

ref_table_conf = {
    'column_definitions': ref_constants.COLUMNS,
    'column_mappings': [
        # Columns:
        # column_map_key, phase, source_table, source_column, target_table, target_column, transformation_rule, stored_proc_name, stored_proc_created_date, created_date

        #Json to Integration
        ('1', 'LZ_JSON', 'identification.Guid', 'INT_SBAC_STU_REG_META', 'guid_registration', 'clean', None),
        ('1', 'LZ_JSON', 'identification.AcademicYear', 'INT_SBAC_STU_REG_META', 'academic_year', 'clean', None),
        ('1', 'LZ_JSON', 'identification.ExtractDate', 'INT_SBAC_STU_REG_META', 'extract_date', 'srDate', None),
        ('1', 'LZ_JSON', 'source.TestRegSysID', 'INT_SBAC_STU_REG_META', 'test_reg_id', 'clean', None),
        # CSV to Staging
        ('1', 'LZ_CSV', 'statename', 'STG_SBAC_STU_REG', 'name_state', 'clean', None),
        ('1', 'LZ_CSV', 'stateabbreviation', 'STG_SBAC_STU_REG', 'code_state', 'cleanUpper', None),
        ('1', 'LZ_CSV', 'responsibledistrictidentifier', 'STG_SBAC_STU_REG', 'guid_district', 'clean', None),
        ('1', 'LZ_CSV', 'organizationname', 'STG_SBAC_STU_REG', 'name_district', 'clean', None),
        ('1', 'LZ_CSV', 'responsibleschoolidentifier', 'STG_SBAC_STU_REG', 'guid_school', 'clean', None),
        ('1', 'LZ_CSV', 'nameofinstitution', 'STG_SBAC_STU_REG', 'name_school', 'clean', None),
        ('1', 'LZ_CSV', 'studentidentifier', 'STG_SBAC_STU_REG', 'guid_student', 'clean', None),
        ('1', 'LZ_CSV', 'externalssid', 'STG_SBAC_STU_REG', 'external_ssid_student', 'clean', None),
        ('1', 'LZ_CSV', 'firstname', 'STG_SBAC_STU_REG', 'name_student_first', 'clean', None),
        ('1', 'LZ_CSV', 'middlename', 'STG_SBAC_STU_REG', 'name_student_middle', 'clean', None),
        ('1', 'LZ_CSV', 'lastorsurname', 'STG_SBAC_STU_REG', 'name_student_last', 'clean', None),
        ('1', 'LZ_CSV', 'sex', 'STG_SBAC_STU_REG', 'gender_student', 'srGender', None),
        ('1', 'LZ_CSV', 'birthdate', 'STG_SBAC_STU_REG', 'dob_student', 'srDate', None),
        ('1', 'LZ_CSV', 'gradelevelwhenassessed', 'STG_SBAC_STU_REG', 'grade_enrolled', 'clean', None),
        ('1', 'LZ_CSV', 'hispanicorlatinoethnicity', 'STG_SBAC_STU_REG', 'dmg_eth_hsp', 'srYn', None),
        ('1', 'LZ_CSV', 'americanindianoralaskanative', 'STG_SBAC_STU_REG', 'dmg_eth_ami', 'srYn', None),
        ('1', 'LZ_CSV', 'asian', 'STG_SBAC_STU_REG', 'dmg_eth_asn', 'srYn', None),
        ('1', 'LZ_CSV', 'blackorafricanamerican', 'STG_SBAC_STU_REG', 'dmg_eth_blk', 'srYn', None),
        ('1', 'LZ_CSV', 'nativehawaiianorotherpacificislander', 'STG_SBAC_STU_REG', 'dmg_eth_pcf', 'srYn', None),
        ('1', 'LZ_CSV', 'white', 'STG_SBAC_STU_REG', 'dmg_eth_wht', 'srYn', None),
        ('1', 'LZ_CSV', 'ideaindicator', 'STG_SBAC_STU_REG', 'dmg_prg_iep', 'srYn', None),
        ('1', 'LZ_CSV', 'lepstatus', 'STG_SBAC_STU_REG', 'dmg_prg_lep', 'srYn', None),
        ('1', 'LZ_CSV', '504status', 'STG_SBAC_STU_REG', 'dmg_prg_504', 'srYn', None),
        ('1', 'LZ_CSV', 'economicdisadvantagestatus', 'STG_SBAC_STU_REG', 'dmg_sts_ecd', 'srYn', None),
        ('1', 'LZ_CSV', 'migrantstatus', 'STG_SBAC_STU_REG', 'dmg_sts_mig', 'srYn', None),
        ('1', 'LZ_CSV', 'demographicracetwoormoreraces', 'STG_SBAC_STU_REG', 'dmg_multi_race', 'srYn', None),
        ('1', 'LZ_CSV', 'confirmationcode', 'STG_SBAC_STU_REG', 'code_confirm', 'clean', None),
        ('1', 'LZ_CSV', 'languagecode', 'STG_SBAC_STU_REG', 'code_language', 'clean', None),
        ('1', 'LZ_CSV', 'englishlanguageproficienclevel', 'STG_SBAC_STU_REG', 'eng_prof_lvl', 'clean', None),
        ('1', 'LZ_CSV', 'firstentrydateintousschool', 'STG_SBAC_STU_REG', 'us_school_entry_date', 'srDate', None),
        ('1', 'LZ_CSV', 'limitedenglishproficiencyentrydate', 'STG_SBAC_STU_REG', 'lep_entry_date', 'srDate', None),
        ('1', 'LZ_CSV', 'lepexitdate', 'STG_SBAC_STU_REG', 'lep_exit_date', 'srDate', None),
        ('1', 'LZ_CSV', 'titleiiilanguageinstructionprogramtype', 'STG_SBAC_STU_REG', 't3_program_type', 'clean', None),
        ('1', 'LZ_CSV', 'primarydisabilitytype', 'STG_SBAC_STU_REG', 'prim_disability_type', 'clean', None),
        # Staging to Integration
        ('3', 'STG_SBAC_STU_REG', 'guid_batch', 'INT_SBAC_STU_REG', 'guid_batch', None, None),
        ('3', 'STG_SBAC_STU_REG', 'name_state', 'INT_SBAC_STU_REG', 'name_state', None, 'substr({src_column}, 1, {length})'),
        ('3', 'STG_SBAC_STU_REG', 'code_state', 'INT_SBAC_STU_REG', 'code_state', None, 'substr({src_column}, 1, {length})'),
        ('3', 'STG_SBAC_STU_REG', 'guid_district', 'INT_SBAC_STU_REG', 'guid_district', None, 'substr({src_column}, 1, {length})'),
        ('3', 'STG_SBAC_STU_REG', 'name_district', 'INT_SBAC_STU_REG', 'name_district', None, 'substr({src_column}, 1, {length})'),
        ('3', 'STG_SBAC_STU_REG', 'guid_school', 'INT_SBAC_STU_REG', 'guid_school', None, 'substr({src_column}, 1, {length})'),
        ('3', 'STG_SBAC_STU_REG', 'name_school', 'INT_SBAC_STU_REG', 'name_school', None, 'substr({src_column}, 1, {length})'),
        ('3', 'STG_SBAC_STU_REG', 'guid_student', 'INT_SBAC_STU_REG', 'guid_student', None, 'substr({src_column}, 1, {length})'),
        ('3', 'STG_SBAC_STU_REG', 'external_ssid_student', 'INT_SBAC_STU_REG', 'external_ssid_student', None, 'substr({src_column}, 1, {length})'),
        ('3', 'STG_SBAC_STU_REG', 'name_student_first', 'INT_SBAC_STU_REG', 'name_student_first', None, 'substr({src_column}, 1, {length})'),
        ('3', 'STG_SBAC_STU_REG', 'name_student_middle', 'INT_SBAC_STU_REG', 'name_student_middle', None, 'substr({src_column}, 1, {length})'),
        ('3', 'STG_SBAC_STU_REG', 'name_student_last', 'INT_SBAC_STU_REG', 'name_student_last', None, 'substr({src_column}, 1, {length})'),
        ('3', 'STG_SBAC_STU_REG', 'gender_student', 'INT_SBAC_STU_REG', 'gender_student', None, 'substr({src_column}, 1, {length})'),
        ('3', 'STG_SBAC_STU_REG', 'dob_student', 'INT_SBAC_STU_REG', 'dob_student', None, 'substr({src_column}, 1, {length})'),
        ('3', 'STG_SBAC_STU_REG', 'grade_enrolled', 'INT_SBAC_STU_REG', 'grade_enrolled', None, 'substr({src_column}, 1, {length})'),
        ('3', 'STG_SBAC_STU_REG', 'dmg_eth_hsp', 'INT_SBAC_STU_REG', 'dmg_eth_hsp', None, 'cast({src_column} as bool)'),
        ('3', 'STG_SBAC_STU_REG', 'dmg_eth_ami', 'INT_SBAC_STU_REG', 'dmg_eth_ami', None, 'cast({src_column} as bool)'),
        ('3', 'STG_SBAC_STU_REG', 'dmg_eth_asn', 'INT_SBAC_STU_REG', 'dmg_eth_asn', None, 'cast({src_column} as bool)'),
        ('3', 'STG_SBAC_STU_REG', 'dmg_eth_blk', 'INT_SBAC_STU_REG', 'dmg_eth_blk', None, 'cast({src_column} as bool)'),
        ('3', 'STG_SBAC_STU_REG', 'dmg_eth_pcf', 'INT_SBAC_STU_REG', 'dmg_eth_pcf', None, 'cast({src_column} as bool)'),
        ('3', 'STG_SBAC_STU_REG', 'dmg_eth_wht', 'INT_SBAC_STU_REG', 'dmg_eth_wht', None, 'cast({src_column} as bool)'),
        ('3', 'STG_SBAC_STU_REG', 'dmg_prg_iep', 'INT_SBAC_STU_REG', 'dmg_prg_iep', None, 'cast({src_column} as bool)'),
        ('3', 'STG_SBAC_STU_REG', 'dmg_prg_lep', 'INT_SBAC_STU_REG', 'dmg_prg_lep', None, 'cast({src_column} as bool)'),
        ('3', 'STG_SBAC_STU_REG', 'dmg_prg_504', 'INT_SBAC_STU_REG', 'dmg_prg_504', None, 'cast({src_column} as bool)'),
        ('3', 'STG_SBAC_STU_REG', 'dmg_sts_ecd', 'INT_SBAC_STU_REG', 'dmg_sts_ecd', None, 'cast({src_column} as bool)'),
        ('3', 'STG_SBAC_STU_REG', 'dmg_sts_mig', 'INT_SBAC_STU_REG', 'dmg_sts_mig', None, 'cast({src_column} as bool)'),
        ('3', 'STG_SBAC_STU_REG', 'dmg_multi_race', 'INT_SBAC_STU_REG', 'dmg_multi_race', None, 'cast({src_column} as bool)'),
        ('3', 'STG_SBAC_STU_REG', 'code_confirm', 'INT_SBAC_STU_REG', 'code_confirm', None, 'substr({src_column}, 1, {length})'),
        ('3', 'STG_SBAC_STU_REG', 'code_language', 'INT_SBAC_STU_REG', 'code_language', None, 'substr({src_column}, 1, {length})'),
        ('3', 'STG_SBAC_STU_REG', 'eng_prof_lvl', 'INT_SBAC_STU_REG', 'eng_prof_lvl', None, 'substr({src_column}, 1, {length})'),
        ('3', 'STG_SBAC_STU_REG', 'us_school_entry_date', 'INT_SBAC_STU_REG', 'us_school_entry_date', None, 'substr({src_column}, 1, {length})'),
        ('3', 'STG_SBAC_STU_REG', 'lep_entry_date', 'INT_SBAC_STU_REG', 'lep_entry_date', None, 'substr({src_column}, 1, {length})'),
        ('3', 'STG_SBAC_STU_REG', 'lep_exit_date', 'INT_SBAC_STU_REG', 'lep_exit_date', None, 'substr({src_column}, 1, {length})'),
        ('3', 'STG_SBAC_STU_REG', 't3_program_type', 'INT_SBAC_STU_REG', 't3_program_type', None, 'substr({src_column}, 1, {length})'),
        ('3', 'STG_SBAC_STU_REG', 'prim_disability_type', 'INT_SBAC_STU_REG', 'prim_disability_type', None, 'substr({src_column}, 1, {length})'),
        ('3', 'STG_SBAC_STU_REG', 'created_date', 'INT_SBAC_STU_REG', 'created_date', None, None),
        #Integration to Target
        ('4', 'INT_SBAC_STU_REG', 'nextval(\'"GLOBAL_REC_SEQ"\')', 'student_reg', 'student_reg_rec_id', None, None),
        ('4', 'INT_SBAC_STU_REG', 'guid_batch', 'student_reg', 'batch_guid', None, None),
        ('4', 'INT_SBAC_STU_REG', 'name_state', 'student_reg', 'state_name', None, None),
        ('4', 'INT_SBAC_STU_REG', 'code_state', 'student_reg', 'state_code', None, None),
        ('4', 'INT_SBAC_STU_REG', 'guid_district', 'student_reg', 'district_guid', None, None),
        ('4', 'INT_SBAC_STU_REG', 'name_district', 'student_reg', 'district_name', None, None),
        ('4', 'INT_SBAC_STU_REG', 'guid_school', 'student_reg', 'school_guid', None, None),
        ('4', 'INT_SBAC_STU_REG', 'name_school', 'student_reg', 'school_name', None, None),
        ('4', 'INT_SBAC_STU_REG', 'guid_student', 'student_reg', 'student_guid', None, None),
        ('4', 'INT_SBAC_STU_REG', 'external_ssid_student', 'student_reg', 'external_student_ssid', None, None),
        ('4', 'INT_SBAC_STU_REG', 'name_student_first', 'student_reg', 'student_first_name', None, None),
        ('4', 'INT_SBAC_STU_REG', 'name_student_middle', 'student_reg', 'student_middle_name', None, None),
        ('4', 'INT_SBAC_STU_REG', 'name_student_last', 'student_reg', 'student_last_name', None, None),
        ('4', 'INT_SBAC_STU_REG', 'gender_student', 'student_reg', 'gender', None, None),
        ('4', 'INT_SBAC_STU_REG', 'dob_student', 'student_reg', 'student_dob', None, None),
        ('4', 'INT_SBAC_STU_REG', 'grade_enrolled', 'student_reg', 'enrl_grade', None, None),
        ('4', 'INT_SBAC_STU_REG', 'dmg_eth_hsp', 'student_reg', 'dmg_eth_hsp', None, None),
        ('4', 'INT_SBAC_STU_REG', 'dmg_eth_ami', 'student_reg', 'dmg_eth_ami', None, None),
        ('4', 'INT_SBAC_STU_REG', 'dmg_eth_asn', 'student_reg', 'dmg_eth_asn', None, None),
        ('4', 'INT_SBAC_STU_REG', 'dmg_eth_blk', 'student_reg', 'dmg_eth_blk', None, None),
        ('4', 'INT_SBAC_STU_REG', 'dmg_eth_pcf', 'student_reg', 'dmg_eth_pcf', None, None),
        ('4', 'INT_SBAC_STU_REG', 'dmg_eth_wht', 'student_reg', 'dmg_eth_wht', None, None),
        ('4', 'INT_SBAC_STU_REG', 'dmg_prg_iep', 'student_reg', 'dmg_prg_iep', None, None),
        ('4', 'INT_SBAC_STU_REG', 'dmg_prg_lep', 'student_reg', 'dmg_prg_lep', None, None),
        ('4', 'INT_SBAC_STU_REG', 'dmg_prg_504', 'student_reg', 'dmg_prg_504', None, None),
        ('4', 'INT_SBAC_STU_REG', 'dmg_sts_ecd', 'student_reg', 'dmg_sts_ecd', None, None),
        ('4', 'INT_SBAC_STU_REG', 'dmg_sts_mig', 'student_reg', 'dmg_sts_mig', None, None),
        ('4', 'INT_SBAC_STU_REG', 'dmg_multi_race', 'student_reg', 'dmg_multi_race', None, None),
        ('4', 'INT_SBAC_STU_REG', 'code_confirm', 'student_reg', 'confirm_code', None, None),
        ('4', 'INT_SBAC_STU_REG', 'code_language', 'student_reg', 'language_code', None, None),
        ('4', 'INT_SBAC_STU_REG', 'eng_prof_lvl', 'student_reg', 'eng_prof_lvl', None, None),
        ('4', 'INT_SBAC_STU_REG', 'us_school_entry_date', 'student_reg', 'us_school_entry_date', None, None),
        ('4', 'INT_SBAC_STU_REG', 'lep_entry_date', 'student_reg', 'lep_entry_date', None, None),
        ('4', 'INT_SBAC_STU_REG', 'lep_exit_date', 'student_reg', 'lep_exit_date', None, None),
        ('4', 'INT_SBAC_STU_REG', 't3_program_type', 'student_reg', 't3_program_type', None, None),
        ('4', 'INT_SBAC_STU_REG', 'prim_disability_type', 'student_reg', 'prim_disability_type', None, None),
        #Integration Meta to Target
        ('4', 'INT_SBAC_STU_REG_META', 'guid_registration', 'student_reg', 'student_reg_guid', None, None),
        ('4', 'INT_SBAC_STU_REG_META', 'academic_year', 'student_reg', 'academic_year', None, None),
        ('4', 'INT_SBAC_STU_REG_META', 'extract_date', 'student_reg', 'extract_date', None, None),
        ('4', 'INT_SBAC_STU_REG_META', 'test_reg_id', 'student_reg', 'reg_system_id', None, None),
    ]
}
