"""
Define the output format for SBAC assessment and registration data.

@author, nestep
@date, February 24, 2014
"""

FAO_VW_FORMAT = {'format': 'csv',
                 'name': 'fact_asmt_outcome_vw.csv',
                 'columns': [{'name': 'asmt_outcome_vw_rec_id', 'val': 'assessment_outcome.rec_id'},
                             {'name': 'asmt_rec_id', 'val': 'assessment.rec_id'},
                             {'name': 'student_rec_id', 'val': 'student.rec_id'},
                             {'name': 'inst_hier_rec_id', 'val': 'institution_hierarchy.rec_id'},
                             {'name': 'asmt_guid', 'val': 'assessment.guid_sr'},
                             {'name': 'student_guid', 'val': 'student.guid_sr'},
                             {'name': 'state_code', 'val': 'state.code'},
                             {'name': 'district_guid', 'val': 'district.guid_sr'},
                             {'name': 'school_guid', 'val': 'school.guid_sr'},
                             {'name': 'where_taken_id', 'val': 'school.guid_sr'},
                             {'name': 'where_taken_name', 'val': 'school.name'},
                             {'name': 'asmt_type', 'val': 'assessment.asmt_type'},
                             {'name': 'asmt_year', 'val': 'assessment.period_year'},
                             {'name': 'asmt_subject', 'val': 'assessment.subject'},
                             {'name': 'asmt_grade', 'val': 'student.grade'},
                             {'name': 'enrl_grade', 'val': 'student.grade'},
                             {'name': 'group_1_id', 'val': 'assessment_outcome.group_1_id'},
                             {'name': 'group_1_text', 'val': 'assessment_outcome.group_1_text'},
                             {'name': 'group_2_id', 'val': 'assessment_outcome.group_2_id'},
                             {'name': 'group_2_text', 'val': 'assessment_outcome.group_2_text'},
                             {'name': 'date_taken', 'val': 'assessment_outcome.date_taken', 'filter': 'date_Ymd'},
                             {'name': 'date_taken_day', 'val': 'assessment_outcome.date_taken', 'filter': 'date_d'},
                             {'name': 'date_taken_month', 'val': 'assessment_outcome.date_taken', 'filter': 'date_m'},
                             {'name': 'date_taken_year', 'val': 'assessment_outcome.date_taken', 'filter': 'date_Y'},
                             {'name': 'asmt_score', 'val': 'assessment_outcome.overall_score'},
                             {'name': 'asmt_score_range_min', 'val': 'assessment_outcome.overall_score_range_min'},
                             {'name': 'asmt_score_range_max', 'val': 'assessment_outcome.overall_score_range_max'},
                             {'name': 'asmt_perf_lvl', 'val': 'assessment_outcome.overall_perf_lvl'},
                             {'name': 'asmt_claim_1_score', 'val': 'assessment_outcome.claim_1_score'},
                             {'name': 'asmt_claim_1_score_range_min', 'val': 'assessment_outcome.claim_1_score_range_min'},
                             {'name': 'asmt_claim_1_score_range_max', 'val': 'assessment_outcome.claim_1_score_range_max'},
                             {'name': 'asmt_claim_1_perf_lvl', 'val': 'assessment_outcome.claim_1_perf_lvl'},
                             {'name': 'asmt_claim_2_score', 'val': 'assessment_outcome.claim_2_score'},
                             {'name': 'asmt_claim_2_score_range_min', 'val': 'assessment_outcome.claim_2_score_range_min'},
                             {'name': 'asmt_claim_2_score_range_max', 'val': 'assessment_outcome.claim_2_score_range_max'},
                             {'name': 'asmt_claim_2_perf_lvl', 'val': 'assessment_outcome.claim_2_perf_lvl'},
                             {'name': 'asmt_claim_3_score', 'val': 'assessment_outcome.claim_3_score'},
                             {'name': 'asmt_claim_3_score_range_min', 'val': 'assessment_outcome.claim_3_score_range_min'},
                             {'name': 'asmt_claim_3_score_range_max', 'val': 'assessment_outcome.claim_3_score_range_max'},
                             {'name': 'asmt_claim_3_perf_lvl', 'val': 'assessment_outcome.claim_3_perf_lvl'},
                             {'name': 'asmt_claim_4_score', 'val': 'assessment_outcome.claim_4_score'},
                             {'name': 'asmt_claim_4_score_range_min', 'val': 'assessment_outcome.claim_4_score_range_min'},
                             {'name': 'asmt_claim_4_score_range_max', 'val': 'assessment_outcome.claim_4_score_range_max'},
                             {'name': 'asmt_claim_4_perf_lvl', 'val': 'assessment_outcome.claim_4_perf_lvl'},
                             {'name': 'sex', 'val': 'student.gender'},
                             {'name': 'dmg_eth_derived', 'val': 'student.derived_demographic'},
                             {'name': 'dmg_eth_hsp', 'val': 'student.eth_hispanic'},
                             {'name': 'dmg_eth_ami', 'val': 'student.eth_amer_ind'},
                             {'name': 'dmg_eth_asn', 'val': 'student.eth_asian'},
                             {'name': 'dmg_eth_blk', 'val': 'student.eth_black'},
                             {'name': 'dmg_eth_pcf', 'val': 'student.eth_pacific'},
                             {'name': 'dmg_eth_wht', 'val': 'student.eth_white'},
                             {'name': 'dmg_eth_2om', 'val': 'student.eth_multi'},
                             {'name': 'dmg_eth_iep', 'val': 'student.prg_iep'},
                             {'name': 'dmg_prg_lep', 'val': 'student.prg_lep'},
                             {'name': 'dmg_prg_504', 'val': 'student.prg_sec504'},
                             {'name': 'dmg_sts_ecd', 'val': 'student.prg_econ_disad'},
                             {'name': 'dmg_sts_mig', 'val': 'student.prg_migrant'},
                             {'name': 'acc_asl_video_embed', 'val': 'assessment_outcome.acc_asl_video_embed'},
                             {'name': 'acc_asl_human_nonembed',
                                      'val': 'assessment_outcome.acc_asl_human_nonembed'},
                             {'name': 'acc_braile_embed', 'val': 'assessment_outcome.acc_braile_embed'},
                             {'name': 'acc_closed_captioning_embed',
                                      'val': 'assessment_outcome.acc_closed_captioning_embed'},
                             {'name': 'acc_text_to_speech_embed', 'val': 'assessment_outcome.acc_text_to_speech_embed'},
                             {'name': 'acc_abacus_nonembed', 'val': 'assessment_outcome.acc_abacus_nonembed'},
                             {'name': 'acc_alternate_response_options_nonembed',
                                      'val': 'assessment_outcome.acc_alternate_response_options_nonembed'},
                             {'name': 'acc_calculator_nonembed', 'val': 'assessment_outcome.acc_calculator_nonembed'},
                             {'name': 'acc_multiplication_table_nonembed',
                                      'val': 'assessment_outcome.acc_multiplication_table_nonembed'},
                             {'name': 'acc_print_on_demand_nonembed',
                                      'val': 'assessment_outcome.acc_print_on_demand_nonembed'},
                             {'name': 'acc_read_aloud_nonembed', 'val': 'assessment_outcome.acc_read_aloud_nonembed'},
                             {'name': 'acc_scribe_nonembed', 'val': 'assessment_outcome.acc_scribe_nonembed'},
                             {'name': 'acc_speech_to_text_nonembed',
                                      'val': 'assessment_outcome.acc_speech_to_text_nonembed'},
                             {'name': 'acc_streamline_mode', 'val': 'assessment_outcome.acc_streamline_mode'},
                             {'name': 'from_date', 'val': 'assessment_outcome.from_date', 'filter': 'date_Ymd'},
                             {'name': 'to_date', 'val': 'assessment_outcome.to_date', 'filter': 'date_Ymd'},
                             {'name': 'rec_status', 'val': 'assessment_outcome.result_status'},
                             {'name': 'batch_guid', 'val': 'BATCH_GUID'}]}

FAO_FORMAT = {'format': 'csv',
              'name': 'fact_asmt_outcome.csv',
              'columns': [{'name': 'asmt_outcome_rec_id', 'val': 'assessment_outcome.rec_id'},
                          {'name': 'asmt_rec_id', 'val': 'assessment.rec_id'},
                          {'name': 'student_rec_id', 'val': 'student.rec_id'},
                          {'name': 'inst_hier_rec_id', 'val': 'institution_hierarchy.rec_id'},
                          {'name': 'asmt_guid', 'val': 'assessment.guid_sr'},
                          {'name': 'student_guid', 'val': 'student.guid_sr'},
                          {'name': 'state_code', 'val': 'state.code'},
                          {'name': 'district_guid', 'val': 'district.guid_sr'},
                          {'name': 'school_guid', 'val': 'school.guid_sr'},
                          {'name': 'where_taken_id', 'val': 'school.guid_sr'},
                          {'name': 'where_taken_name', 'val': 'school.name'},
                          {'name': 'asmt_grade', 'val': 'student.grade'},
                          {'name': 'enrl_grade', 'val': 'student.grade'},
                          {'name': 'group_1_id', 'val': 'assessment_outcome.group_1_id'},
                          {'name': 'group_1_text', 'val': 'assessment_outcome.group_1_text'},
                          {'name': 'group_2_id', 'val': 'assessment_outcome.group_2_id'},
                          {'name': 'group_2_text', 'val': 'assessment_outcome.group_2_text'},
                          {'name': 'date_taken', 'val': 'assessment_outcome.date_taken', 'filter': 'date_Ymd'},
                          {'name': 'date_taken_day', 'val': 'assessment_outcome.date_taken', 'filter': 'date_d'},
                          {'name': 'date_taken_month', 'val': 'assessment_outcome.date_taken', 'filter': 'date_m'},
                          {'name': 'date_taken_year', 'val': 'assessment_outcome.date_taken', 'filter': 'date_Y'},
                          {'name': 'asmt_score', 'val': 'assessment_outcome.overall_score'},
                          {'name': 'asmt_score_range_min', 'val': 'assessment_outcome.overall_score_range_min'},
                          {'name': 'asmt_score_range_max', 'val': 'assessment_outcome.overall_score_range_max'},
                          {'name': 'asmt_perf_lvl', 'val': 'assessment_outcome.overall_perf_lvl'},
                          {'name': 'asmt_claim_1_score', 'val': 'assessment_outcome.claim_1_score'},
                          {'name': 'asmt_claim_1_score_range_min', 'val': 'assessment_outcome.claim_1_score_range_min'},
                          {'name': 'asmt_claim_1_score_range_max', 'val': 'assessment_outcome.claim_1_score_range_max'},
                          {'name': 'asmt_claim_1_perf_lvl', 'val': 'assessment_outcome.claim_1_perf_lvl'},
                          {'name': 'asmt_claim_2_score', 'val': 'assessment_outcome.claim_2_score'},
                          {'name': 'asmt_claim_2_score_range_min', 'val': 'assessment_outcome.claim_2_score_range_min'},
                          {'name': 'asmt_claim_2_score_range_max', 'val': 'assessment_outcome.claim_2_score_range_max'},
                          {'name': 'asmt_claim_2_perf_lvl', 'val': 'assessment_outcome.claim_2_perf_lvl'},
                          {'name': 'asmt_claim_3_score', 'val': 'assessment_outcome.claim_3_score'},
                          {'name': 'asmt_claim_3_score_range_min', 'val': 'assessment_outcome.claim_3_score_range_min'},
                          {'name': 'asmt_claim_3_score_range_max', 'val': 'assessment_outcome.claim_3_score_range_max'},
                          {'name': 'asmt_claim_3_perf_lvl', 'val': 'assessment_outcome.claim_3_perf_lvl'},
                          {'name': 'asmt_claim_4_score', 'val': 'assessment_outcome.claim_4_score'},
                          {'name': 'asmt_claim_4_score_range_min', 'val': 'assessment_outcome.claim_4_score_range_min'},
                          {'name': 'asmt_claim_4_score_range_max', 'val': 'assessment_outcome.claim_4_score_range_max'},
                          {'name': 'asmt_claim_4_perf_lvl', 'val': 'assessment_outcome.claim_4_perf_lvl'},
                          {'name': 'acc_asl_video_embed', 'val': 'assessment_outcome.acc_asl_video_embed'},
                          {'name': 'acc_asl_human_nonembed',
                                   'val': 'assessment_outcome.acc_asl_human_nonembed'},
                          {'name': 'acc_braile_embed', 'val': 'assessment_outcome.acc_braile_embed'},
                          {'name': 'acc_closed_captioning_embed',
                                   'val': 'assessment_outcome.acc_closed_captioning_embed'},
                          {'name': 'acc_text_to_speech_embed', 'val': 'assessment_outcome.acc_text_to_speech_embed'},
                          {'name': 'acc_abacus_nonembed', 'val': 'assessment_outcome.acc_abacus_nonembed'},
                          {'name': 'acc_alternate_response_options_nonembed',
                                   'val': 'assessment_outcome.acc_alternate_response_options_nonembed'},
                          {'name': 'acc_calculator_nonembed', 'val': 'assessment_outcome.acc_calculator_nonembed'},
                          {'name': 'acc_multiplication_table_nonembed',
                                   'val': 'assessment_outcome.acc_multiplication_table_nonembed'},
                          {'name': 'acc_print_on_demand_nonembed',
                                   'val': 'assessment_outcome.acc_print_on_demand_nonembed'},
                          {'name': 'acc_read_aloud_nonembed', 'val': 'assessment_outcome.acc_read_aloud_nonembed'},
                          {'name': 'acc_scribe_nonembed', 'val': 'assessment_outcome.acc_scribe_nonembed'},
                          {'name': 'acc_speech_to_text_nonembed',
                                   'val': 'assessment_outcome.acc_speech_to_text_nonembed'},
                          {'name': 'acc_streamline_mode', 'val': 'assessment_outcome.acc_streamline_mode'},
                          {'name': 'from_date', 'val': 'assessment_outcome.from_date', 'filter': 'date_Ymd'},
                          {'name': 'to_date', 'val': 'assessment_outcome.to_date', 'filter': 'date_Ymd'},
                          {'name': 'rec_status', 'val': 'assessment_outcome.result_status'},
                          {'name': 'batch_guid', 'val': 'BATCH_GUID'}]}

DIM_STUDENT_FORMAT = {'format': 'csv',
                      'name': 'dim_student.csv',
                      'columns': [{'name': 'student_rec_id', 'val': 'student.rec_id'},
                                  {'name': 'student_guid', 'val': 'student.guid_sr'},
                                  {'name': 'external_student_id', 'val': 'student.external_ssid_sr'},
                                  {'name': 'first_name', 'val': 'student.first_name'},
                                  {'name': 'middle_name', 'val': 'student.middle_name'},
                                  {'name': 'last_name', 'val': 'student.last_name'},
                                  {'name': 'birthdate', 'val': 'student.dob', 'filter': 'date_Ymd'},
                                  {'name': 'sex', 'val': 'student.gender'},
                                  {'name': 'dmg_eth_derived', 'val': 'student.derived_demographic'},
                                  {'name': 'dmg_eth_hsp', 'val': 'student.eth_hispanic'},
                                  {'name': 'dmg_eth_ami', 'val': 'student.eth_amer_ind'},
                                  {'name': 'dmg_eth_asn', 'val': 'student.eth_asian'},
                                  {'name': 'dmg_eth_blk', 'val': 'student.eth_black'},
                                  {'name': 'dmg_eth_pcf', 'val': 'student.eth_pacific'},
                                  {'name': 'dmg_eth_wht', 'val': 'student.eth_white'},
                                  {'name': 'dmg_eth_2om', 'val': 'student.eth_multi'},
                                  {'name': 'dmg_eth_iep', 'val': 'student.prg_iep'},
                                  {'name': 'dmg_prg_lep', 'val': 'student.prg_lep'},
                                  {'name': 'dmg_prg_504', 'val': 'student.prg_sec504'},
                                  {'name': 'dmg_sts_ecd', 'val': 'student.prg_econ_disad'},
                                  {'name': 'dmg_sts_mig', 'val': 'student.prg_migrant'},
                                  {'name': 'from_date', 'val': '20130901'},
                                  {'name': 'to_date', 'val': '99991231'},
                                  {'name': 'rec_status', 'val': 'C'},
                                  {'name': 'batch_guid', 'val': 'BATCH_GUID'}]}

DIM_INST_HIER_FORMAT = {'format': 'csv',
                        'name': 'dim_inst_hier.csv',
                        'columns': [{'name': 'inst_hier_rec_id', 'val': 'institution_hierarchy.rec_id'},
                                    {'name': 'state_code', 'val': 'state.code'},
                                    {'name': 'district_guid', 'val': 'district.guid_sr'},
                                    {'name': 'district_name', 'val': 'district.name'},
                                    {'name': 'school_guid', 'val': 'school.guid_sr'},
                                    {'name': 'school_name', 'val': 'school.name'},
                                    {'name': 'from_date', 'val': 'institution_hierarchy.from_date',
                                     'filter': 'date_Ymd'},
                                    {'name': 'to_date', 'val': 'institution_hierarchy.to_date', 'filter': 'date_Ymd'},
                                    {'name': 'rec_status', 'val': 'C'},
                                    {'name': 'batch_guid', 'val': 'BATCH_GUID'}]}

DIM_ASMT_FORMAT = {'format': 'csv',
                   'name': 'dim_asmt.csv',
                   'columns': [{'name': 'asmt_rec_id', 'val': 'assessment.rec_id'},
                               {'name': 'asmt_guid', 'val': 'assessment.guid_sr'},
                               {'name': 'asmt_type', 'val': 'assessment.asmt_type'},
                               {'name': 'asmt_period', 'val': 'assessment.period'},
                               {'name': 'asmt_period_year', 'val': 'assessment.period_year'},
                               {'name': 'asmt_version', 'val': 'assessment.version'},
                               {'name': 'asmt_subject', 'val': 'assessment.subject'},
                               {'name': 'effective_date', 'val': 'assessment.effective_date', 'filter': 'date_Ymd'},
                               {'name': 'asmt_claim_1_name', 'val': 'assessment.claim_1_name'},
                               {'name': 'asmt_claim_2_name', 'val': 'assessment.claim_2_name'},
                               {'name': 'asmt_claim_3_name', 'val': 'assessment.claim_3_name'},
                               {'name': 'asmt_claim_4_name', 'val': 'assessment.claim_4_name'},
                               {'name': 'asmt_perf_lvl_name_1', 'val': 'assessment.perf_lvl_name_1'},
                               {'name': 'asmt_perf_lvl_name_2', 'val': 'assessment.perf_lvl_name_2'},
                               {'name': 'asmt_perf_lvl_name_3', 'val': 'assessment.perf_lvl_name_3'},
                               {'name': 'asmt_perf_lvl_name_4', 'val': 'assessment.perf_lvl_name_4'},
                               {'name': 'asmt_perf_lvl_name_5', 'val': 'assessment.perf_lvl_name_5'},
                               {'name': 'asmt_claim_perf_lvl_name_1', 'val': 'assessment.claim_perf_lvl_name_1'},
                               {'name': 'asmt_claim_perf_lvl_name_2', 'val': 'assessment.claim_perf_lvl_name_2'},
                               {'name': 'asmt_claim_perf_lvl_name_3', 'val': 'assessment.claim_perf_lvl_name_3'},
                               {'name': 'asmt_score_min', 'val': 'assessment.overall_score_min'},
                               {'name': 'asmt_score_max', 'val': 'assessment.overall_score_max'},
                               {'name': 'asmt_claim_1_score_min', 'val': 'assessment.claim_1_score_min'},
                               {'name': 'asmt_claim_1_score_max', 'val': 'assessment.claim_1_score_max'},
                               {'name': 'asmt_claim_2_score_min', 'val': 'assessment.claim_2_score_min'},
                               {'name': 'asmt_claim_2_score_max', 'val': 'assessment.claim_2_score_max'},
                               {'name': 'asmt_claim_3_score_min', 'val': 'assessment.claim_3_score_min'},
                               {'name': 'asmt_claim_3_score_max', 'val': 'assessment.claim_3_score_max'},
                               {'name': 'asmt_claim_4_score_min', 'val': 'assessment.claim_4_score_min'},
                               {'name': 'asmt_claim_4_score_max', 'val': 'assessment.claim_4_score_max'},
                               {'name': 'asmt_cut_point_1', 'val': 'assessment.overall_cut_point_1'},
                               {'name': 'asmt_cut_point_2', 'val': 'assessment.overall_cut_point_2'},
                               {'name': 'asmt_cut_point_3', 'val': 'assessment.overall_cut_point_3'},
                               {'name': 'asmt_cut_point_4', 'val': 'assessment.overall_cut_point_4'},
                               {'name': 'from_date', 'val': 'assessment.from_date', 'filter': 'date_Ymd'},
                               {'name': 'to_date', 'val': 'assessment.to_date', 'filter': 'date_Ymd'},
                               {'name': 'rec_status', 'val': 'C'},
                               {'name': 'batch_guid', 'val': 'BATCH_GUID'}]}

STUDENT_REG_FORMAT = {'format': 'csv',
                      'name': 'student_reg.csv',
                      'columns': [{'name': 'student_reg_rec_id', 'val': 'student.rec_id_sr'},
                                  {'name': 'state_code', 'val': 'state.code'},
                                  {'name': 'district_guid', 'val': 'district.guid_sr'},
                                  {'name': 'district_name', 'val': 'district.name'},
                                  {'name': 'school_guid', 'val': 'school.guid_sr'},
                                  {'name': 'school_name', 'val': 'school.name'},
                                  {'name': 'student_guid', 'val': 'student.guid_sr'},
                                  {'name': 'external_student_ssid', 'val': 'student.external_ssid_sr'},
                                  {'name': 'first_name', 'val': 'student.first_name'},
                                  {'name': 'middle_name', 'val': 'student.middle_name'},
                                  {'name': 'last_name', 'val': 'student.last_name'},
                                  {'name': 'birthdate', 'val': 'student.dob', 'filter': 'date_Y_m_d'},
                                  {'name': 'sex', 'val': 'student.gender'},
                                  {'name': 'enrl_grade', 'val': 'student.grade', 'filter': 'zero_pad_grade'},
                                  {'name': 'dmg_eth_hsp', 'val': 'student.eth_hispanic'},
                                  {'name': 'dmg_eth_ami', 'val': 'student.eth_amer_ind'},
                                  {'name': 'dmg_eth_asn', 'val': 'student.eth_asian'},
                                  {'name': 'dmg_eth_blk', 'val': 'student.eth_black'},
                                  {'name': 'dmg_eth_pcf', 'val': 'student.eth_pacific'},
                                  {'name': 'dmg_eth_wht', 'val': 'student.eth_white'},
                                  {'name': 'dmg_multi_race', 'val': 'student.eth_multi'},
                                  {'name': 'dmg_eth_iep', 'val': 'student.prg_iep'},
                                  {'name': 'dmg_prg_lep', 'val': 'student.prg_lep'},
                                  {'name': 'dmg_prg_504', 'val': 'student.prg_sec504'},
                                  {'name': 'dmg_sts_ecd', 'val': 'student.prg_econ_disad'},
                                  {'name': 'dmg_sts_mig', 'val': 'student.prg_migrant'},
                                  {'name': 'confirm_code', 'val': 'student.first_name'},
                                  {'name': 'language_code', 'val': 'student.lang_code'},
                                  {'name': 'eng_prof_lvl', 'val': 'student.lang_prof_level'},
                                  {'name': 'us_school_entry_date', 'val': 'student.school_entry_date',
                                   'filter': 'date_Y_m_d'},
                                  {'name': 'lep_entry_date', 'val': 'student.prg_lep_entry_date',
                                   'filter': 'date_Y_m_d'},
                                  {'name': 'lep_exit_date', 'val': 'student.prg_lep_exit_date', 'filter': 'date_Y_m_d'},
                                  {'name': 't3_program_type', 'val': 'student.lang_title_3_prg'},
                                  {'name': 'prim_disability_type', 'val': 'student.prg_primary_disability'},
                                  {'name': 'student_reg_guid', 'val': 'registration_system.guid'},
                                  {'name': 'academic_year', 'val': 'registration_system.academic_year'},
                                  {'name': 'extract_date', 'val': 'registration_system.extract_date',
                                   'filter': 'date_Y_m_d'},
                                  {'name': 'reg_system_id', 'val': 'registration_system.sys_guid'},
                                  {'name': 'batch_guid', 'val': 'BATCH_GUID'}]}

ASMT_JSON_FORMAT = {'format': 'json',
                    'name': 'METADATA_ASMT_ID_<GUID>.json',
                    'layout': {
                        'content': 'assessment',
                        'Identification': {
                            'Guid': 'assessment.guid_sr',
                            'Year': 'assessment.period_year',
                            'Type': 'assessment.asmt_type',
                            'Period': 'assessment.period',
                            'Subject': 'assessment.subject',
                            'EffectiveDate': 'assessment_effective.date',
                            'Version': 'assessment.version'
                        },
                        'Overall': {
                            'MinScore': 'assessment.overall_score_min',
                            'MaxScore': 'assessment.overall_score_max'
                        },
                        'PerformanceLevels': {
                            'Level1': {
                                'Name': 'assessment.perf_lvl_name_1',
                                'CutPoint': 'assessment.overall_score_min'
                            },
                            'Level2': {
                                'Name': 'assessment.perf_lvl_name_2',
                                'CutPoint': 'assessment.overall_cut_point_1'
                            },
                            'Level3': {
                                'Name': 'assessment.perf_lvl_name_3',
                                'CutPoint': 'assessment.overall_cut_point_2'
                            },
                            'Level4': {
                                'Name': 'assessment.perf_lvl_name_4',
                                'CutPoint': 'assessment.overall_cut_point_3'
                            },
                            'Level5': {
                                'Name': 'assessment.perf_lvl_name_5',
                                'CutPoint': 'assessment.overall_cut_point_4'
                            }
                        },
                        'Claims': {
                            'Claim1': {
                                'Name': 'assessment.claim_1_name',
                                'MinScore': 'assessment.claim_1_score_min',
                                'MaxScore': 'assessment.claim_1_score_max'
                            },
                            'Claim2': {
                                'Name': 'assessment.claim_2_name',
                                'MinScore': 'assessment.claim_2_score_min',
                                'MaxScore': 'assessment.claim_2_score_max'
                            },
                            'Claim3': {
                                'Name': 'assessment.claim_3_name',
                                'MinScore': 'assessment.claim_3_score_min',
                                'MaxScore': 'assessment.claim_3_score_max'
                            },
                            'Claim4': {
                                'Name': 'assessment.claim_4_name',
                                'MinScore': 'assessment.claim_4_score_min',
                                'MaxScore': 'assessment.claim_4_score_max'
                            }
                        },
                        'ClaimsPerformanceLevel': {
                            'Level1': {
                                'Name': 'assessment.claim_perf_lvl_name_1'
                            },
                            'Level2': {
                                'Name': 'assessment.claim_perf_lvl_name_2'
                            },
                            'Level3': {
                                'Name': 'assessment.claim_perf_lvl_name_3'
                            }
                        }
                    }}

LZ_ITEMDATA_FORMAT = {'format': 'csv',
                      'name': '<STUDENT_GUID>.csv',
                      'columns': [{'name': 'key', 'val': 'assessment_outcome_item_data.key'},
                                  {'name': 'student_guid', 'val': 'assessment_outcome_item_data.student_guid'},  # 'student.guid_sr'},
                                  {'name': 'segmentId', 'val': 'assessment_outcome_item_data.segment_id'},
                                  {'name': 'position', 'val': 'assessment_outcome_item_data.position'},
                                  {'name': 'clientId', 'val': '3b6a2490'},
                                  {'name': 'operational', 'val': '0'},
                                  {'name': 'isSelected', 'val': '1'},
                                  {'name': 'format', 'val': 'assessment_outcome_item_data.format'},
                                  {'name': 'score', 'val': '0'},
                                  {'name': 'scoreStatus', 'val': '1'},
                                  {'name': 'adminDate', 'val': '2013-05-03 16:21:44'},
                                  {'name': 'numberVisits', 'val': '1'},
                                  {'name': 'strand', 'val': 'MA-Undesignated'},
                                  {'name': 'contentLevel', 'val': 'MA-Undesignated'},
                                  {'name': 'pageNumber', 'val': '1'},
                                  {'name': 'pageVisits', 'val': '0'},
                                  {'name': 'pageTime', 'val': '0'},
                                  {'name': 'dropped', 'val': '0'}]}

LZ_REALDATA_FORMAT = {'format': 'csv',
                      'name': 'REALDATA_ASMT_ID_<GUID>.csv',
                      'columns': [{'name': 'StateAbbreviation', 'val': 'state.code'},
                                  {'name': 'ResponsibleDistrictIdentifier', 'val': 'district.guid_sr'},
                                  {'name': 'OrganizationName', 'val': 'district.name'},
                                  {'name': 'ResponsibleSchoolIdentifier', 'val': 'school.guid_sr'},
                                  {'name': 'NameOfInstitution', 'val': 'school.name'},
                                  {'name': 'StudentIdentifier', 'val': 'student.guid_sr'},
                                  {'name': 'ExternalSSID', 'val': 'student.external_ssid_sr'},
                                  {'name': 'FirstName', 'val': 'student.first_name'},
                                  {'name': 'MiddleName', 'val': 'student.middle_name'},
                                  {'name': 'LastOrSurname', 'val': 'student.last_name'},
                                  {'name': 'Sex', 'val': 'student.gender'},
                                  {'name': 'Birthdate', 'val': 'student.dob', 'filter': 'date_Ymd'},
                                  {'name': 'GradeLevelWhenAssessed', 'val': 'student.grade'},
                                  {'name': 'HispanicOrLatinoEthnicity', 'val': 'student.eth_hispanic'},
                                  {'name': 'AmericanIndianOrAlaskaNative', 'val': 'student.eth_amer_ind'},
                                  {'name': 'Asian', 'val': 'student.eth_asian'},
                                  {'name': 'BlackOrAfricanAmerican', 'val': 'student.eth_black'},
                                  {'name': 'NativeHawaiianOrOtherPacificIslander', 'val': 'student.eth_pacific'},
                                  {'name': 'White', 'val': 'student.eth_white'},
                                  {'name': 'DemographicRaceTwoOrMoreRaces', 'val': 'student.eth_multi'},
                                  {'name': 'IDEAIndicator', 'val': 'student.prg_iep'},
                                  {'name': 'LEPStatus', 'val': 'student.prg_lep'},
                                  {'name': 'Section504Status', 'val': 'student.prg_sec504'},
                                  {'name': 'EconomicDisadvantageStatus', 'val': 'student.prg_econ_disad'},
                                  {'name': 'MigrantStatus', 'val': 'student.prg_migrant'},
                                  {'name': 'Group1Id', 'val': 'assessment_outcome.group_1_id'},
                                  {'name': 'Group1Text', 'val': 'assessment_outcome.group_1_text'},
                                  {'name': 'Group2Id', 'val': 'assessment_outcome.group_2_id'},
                                  {'name': 'Group2Text', 'val': 'assessment_outcome.group_2_text'},
                                  {'name': 'AssessmentGuid', 'val': 'assessment.guid_sr'},
                                  {'name': 'AssessmentSessionLocationId', 'val': 'school.guid_sr'},
                                  {'name': 'AssessmentSessionLocation', 'val': 'school.name'},
                                  {'name': 'AssessmentAdministrationFinishDate', 'val': 'assessment_outcome.date_taken',
                                   'filter': 'date_Ymd'},
                                  {'name': 'AssessmentYear', 'val': 'assessment.period_year'},
                                  {'name': 'AssessmentType', 'val': 'assessment.asmt_type'},
                                  {'name': 'AssessmentAcademicSubject', 'val': 'assessment.subject'},
                                  {'name': 'AssessmentLevelForWhichDesigned', 'val': 'student.grade'},
                                  {'name': 'AssessmentSubtestResultScoreValue',
                                   'val': 'assessment_outcome.overall_score'},
                                  {'name': 'AssessmentSubtestMinimumValue',
                                   'val': 'assessment_outcome.overall_score_range_min'},
                                  {'name': 'AssessmentSubtestMaximumValue',
                                   'val': 'assessment_outcome.overall_score_range_max'},
                                  {'name': 'AssessmentPerformanceLevelIdentifier',
                                   'val': 'assessment_outcome.overall_perf_lvl'},
                                  {'name': 'AssessmentSubtestResultScoreClaim1Value',
                                   'val': 'assessment_outcome.claim_1_score'},
                                  {'name': 'AssessmentSubtestClaim1MinimumValue',
                                   'val': 'assessment_outcome.claim_1_score_range_min'},
                                  {'name': 'AssessmentSubtestClaim1MaximumValue',
                                   'val': 'assessment_outcome.claim_1_score_range_max'},
                                  {'name': 'AssessmentClaim1PerformanceLevelIdentifier',
                                   'val': 'assessment_outcome.claim_1_perf_lvl'},
                                  {'name': 'AssessmentSubtestResultScoreClaim2Value',
                                   'val': 'assessment_outcome.claim_2_score'},
                                  {'name': 'AssessmentSubtestClaim2MinimumValue',
                                   'val': 'assessment_outcome.claim_2_score_range_min'},
                                  {'name': 'AssessmentSubtestClaim2MaximumValue',
                                   'val': 'assessment_outcome.claim_2_score_range_max'},
                                  {'name': 'AssessmentClaim2PerformanceLevelIdentifier',
                                   'val': 'assessment_outcome.claim_2_perf_lvl'},
                                  {'name': 'AssessmentSubtestResultScoreClaim3Value',
                                   'val': 'assessment_outcome.claim_3_score'},
                                  {'name': 'AssessmentSubtestClaim3MinimumValue',
                                   'val': 'assessment_outcome.claim_3_score_range_min'},
                                  {'name': 'AssessmentSubtestClaim3MaximumValue',
                                   'val': 'assessment_outcome.claim_3_score_range_max'},
                                  {'name': 'AssessmentClaim3PerformanceLevelIdentifier',
                                   'val': 'assessment_outcome.claim_3_perf_lvl'},
                                  {'name': 'AssessmentSubtestResultScoreClaim4Value',
                                   'val': 'assessment_outcome.claim_4_score'},
                                  {'name': 'AssessmentSubtestClaim4MinimumValue',
                                   'val': 'assessment_outcome.claim_4_score_range_min'},
                                  {'name': 'AssessmentSubtestClaim4MaximumValue',
                                   'val': 'assessment_outcome.claim_4_score_range_max'},
                                  {'name': 'AssessmentClaim4PerformanceLevelIdentifier',
                                   'val': 'assessment_outcome.claim_4_perf_lvl'},
                                  {'name': 'AccommodationAmericanSignLanguage',
                                   'val': 'assessment_outcome.acc_asl_video_embed'},
                                  {'name': 'AccommodationSignLanguageHumanIntervention',
                                   'val': 'assessment_outcome.acc_asl_human_nonembed'},
                                  {'name': 'AccommodationBraille', 'val': 'assessment_outcome.acc_braile_embed'},
                                  {'name': 'AccommodationClosedCaptioning',
                                   'val': 'assessment_outcome.acc_closed_captioning_embed'},
                                  {'name': 'AccommodationTextToSpeech',
                                   'val': 'assessment_outcome.acc_text_to_speech_embed'},
                                  {'name': 'AccommodationAbacus', 'val': 'assessment_outcome.acc_abacus_nonembed'},
                                  {'name': 'AccommodationAlternateResponseOptions',
                                   'val': 'assessment_outcome.acc_alternate_response_options_nonembed'},
                                  {'name': 'AccommodationCalculator',
                                   'val': 'assessment_outcome.acc_calculator_nonembed'},
                                  {'name': 'AccommodationMultiplicationTable',
                                   'val': 'assessment_outcome.acc_multiplication_table_nonembed'},
                                  {'name': 'AccommodationPrintOnDemand',
                                   'val': 'assessment_outcome.acc_print_on_demand_nonembed'},
                                  {'name': 'AccommodationReadAloud',
                                   'val': 'assessment_outcome.acc_read_aloud_nonembed'},
                                  {'name': 'AccommodationScribe', 'val': 'assessment_outcome.acc_scribe_nonembed'},
                                  {'name': 'AccommodationSpeechToText',
                                   'val': 'assessment_outcome.acc_speech_to_text_nonembed'},
                                  {'name': 'AccommodationStreamlineMode',
                                   'val': 'assessment_outcome.acc_streamline_mode'},
                                  {'name': 'Op', 'val': 'assessment_outcome.result_status', 'filter': 'only_delete'}]}

SR_FORMAT = {'format': 'csv',
             'name': '<YEAR>_sr_<GUID>.csv',
             'columns': [{'name': 'StateAbbreviation', 'val': 'state.code'},
                         {'name': 'ResponsibleDistrictIdentifier', 'val': 'district.guid_sr'},
                         {'name': 'OrganizationName', 'val': 'district.name'},
                         {'name': 'ResponsibleSchoolIdentifier', 'val': 'school.guid_sr'},
                         {'name': 'NameOfInstitution', 'val': 'school.name'},
                         {'name': 'StudentIdentifier', 'val': 'student.guid_sr'},
                         {'name': 'ExternalSSID', 'val': 'student.external_ssid_sr'},
                         {'name': 'FirstName', 'val': 'student.first_name'},
                         {'name': 'MiddleName', 'val': 'student.middle_name'},
                         {'name': 'LastOrSurname', 'val': 'student.last_name'},
                         {'name': 'Sex', 'val': 'student.gender'},
                         {'name': 'Birthdate', 'val': 'student.dob', 'filter': 'date_Ymd'},
                         {'name': 'GradeLevelWhenAssessed', 'val': 'student.grade'},
                         {'name': 'HispanicOrLatinoEthnicity', 'val': 'student.eth_hispanic', 'filter': 'yesno'},
                         {'name': 'AmericanIndianOrAlaskaNative', 'val': 'student.eth_amer_ind', 'filter': 'yesno'},
                         {'name': 'Asian', 'val': 'student.eth_asian', 'filter': 'yesno'},
                         {'name': 'BlackOrAfricanAmerican', 'val': 'student.eth_black', 'filter': 'yesno'},
                         {'name': 'NativeHawaiianOrOtherPacificIslander', 'val': 'student.eth_pacific',
                          'filter': 'yesno'},
                         {'name': 'White', 'val': 'student.eth_white', 'filter': 'yesno'},
                         {'name': 'IDEAIndicator', 'val': 'student.prg_idea', 'filter': 'yesno'},
                         {'name': 'LEPStatus', 'val': 'student.prg_lep', 'filter': 'yesno'},
                         {'name': 'Section504Status', 'val': 'student.prg_sec504', 'filter': 'yesnoblank'},
                         {'name': 'EconomicDisadvantageStatus', 'val': 'student.prg_econ_disad', 'filter': 'yesno'},
                         {'name': 'MigrantStatus', 'val': 'student.prg_migrant', 'filter': 'yesnoblank'},
                         {'name': 'DemographicRaceTwoOrMoreRaces', 'val': 'student.eth_multi', 'filter': 'yesno'},
                         {'name': 'ConfirmationCode', 'val': 'student.first_name'},
                         {'name': 'LanguageCode', 'val': 'student.lang_code'},
                         {'name': 'EnglishLanguageProficiencLevel', 'val': 'student.lang_prof_level'},
                         {'name': 'FirstEntryDateIntoUSSchool', 'val': 'student.school_entry_date',
                          'filter': 'date_Ymd'},
                         {'name': 'LimitedEnglishProficiencyEntryDate', 'val': 'student.prg_lep_entry_date',
                          'filter': 'date_Ymd'},
                         {'name': 'LEPExitDate', 'val': 'student.prg_lep_exit_date', 'filter': 'date_Ymd'},
                         {'name': 'TitleIIILanguageInstructionProgramType', 'val': 'student.lang_title_3_prg'},
                         {'name': 'PrimaryDisabilityType', 'val': 'student.prg_primary_disability'}]}

REGISTRATION_SYSTEM_FORMAT = {'format': 'json',
                              'name': '<YEAR>_sr_<GUID>.json',
                              'layout': {
                                  'Content': 'StudentRegistration',
                                  'Identification': {
                                      'Guid': 'registration_system.guid',
                                      'AcademicYear': 'registration_system.academic_year',
                                      'ExtractDate': 'registration_system.extract_date'
                                  },
                                  'Source': {
                                      'TestRegSysID': 'registration_system.sys_guid',
                                      'TestRegCallbackURL': 'registration_system.callback_url'
                                  }}}
