#!/bin/bash
#
# chkconfig: 345 90 10

# Source function library.
. /etc/rc.d/init.d/functions
. /opt/virtualenv/edsftp/bin/activate
PIDFILE="/var/run/edsftp-watcher/edsftp-watcher.pid"
EDSFTP_SYNC="python -m edsftp.scripts.sftp_driver --sync -d -p $PIDFILE"

start() {
	echo -n "Starting edsftp sync: "
	daemon $EDSFTP_SYNC
	RETVAL=$?
}

stop() {
	echo -n "Stopping edsftp sync: "
	killproc -p $PIDFILE
	RETVAL=$?
}

check_status() {
    echo -n "Checking edsftp-watcher is running..."
    PID=`ps aux | grep sftp_driver | grep -v grep | awk '{print $2}'`
    if [ -z "$PID" ];
    then
        echo -n "edsftp-watcher is not running"
        echo
    else
        echo -n "edsftp-watcher is running (pid $PID)"
        echo
    fi
}

case $1 in
	start)
		start
	;;
	stop)
		stop
	;;
	restart)
	    stop
	    start
	;;
	status)
	    check_status
	;;
	*)

	echo $"Usage: edsftp-watcher {start|stop|restart|status}"
	exit 2
esac
deactivate
exit $RETVAL
