// Generated by CoffeeScript 1.4.0
(function() {
  var even, evens, _i, _results;

  even = function(number) {
    return !(number % 2);
  };

  evens = function(range) {
    var num, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = range.length; _i < _len; _i++) {
      num = range[_i];
      if (even(num)) {
        _results.push(num);
      }
    }
    return _results;
  };

  console.log(evens((function() {
    _results = [];
    for (_i = 1; _i <= 100; _i++){ _results.push(_i); }
    return _results;
  }).apply(this)));

}).call(this);
