#!/bin/bash
# (c) 2014 The Regents of the University of California. All rights reserved,
# subject to the license below.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use
# this file except in compliance with the License. You may obtain a copy of the
# License at http://www.apache.org/licenses/LICENSE-2.0. Unless required by
# applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the specific language
# governing permissions and limitations under the License.

#
# chkconfig: 345 90 10

# Source function library.
. /etc/rc.d/init.d/functions
. /opt/virtualenv/smarter_score_batcher/bin/activate
PIDFILE="/var/run/smarter_score_batcher/file-monitor-smarter_score_batcher.pid"
FILE_MONITOR="python -m smarter_score_batcher.trigger.file_monitor -d -p $PIDFILE"

start() {
	echo -n "Starting file-monitor-smarter_score_batcher: "
	daemon --user celery $FILE_MONITOR
	echo
	RETVAL=$?
}

stop() {
	echo -n "Stopping file-monitor-smarter_score_batcher: "
	killproc -p $PIDFILE
	echo
	RETVAL=$?
}

check_status() {
    echo -n "Checking file-monitor-smarter_score_batcher is running..."
    PID=`ps aux | grep file_monitor | grep -v grep | awk '{print $2}'`
    if [ -z "$PID" ];
    then
        echo -n "file-monitor-smarter_score_batcher is not running"
        echo
    else
        echo -n "file-monitor-smarter_score_batcher is running (pid $PID)"
        echo
    fi
}

case $1 in
	start)
		start
	;;
	stop)
		stop
	;;
	restart)
	    stop
	    start
	;;
	status)
	    check_status
	;;
	*)

	echo $"Usage: file-monitor-smarter_score_batcher {start|stop|restart|stop}"
	exit 2
esac
deactivate
exit $RETVAL
