#!/bin/bash
#
# chkconfig: 345 90 10

# Source function library.
. /etc/rc.d/init.d/functions
. /opt/virtualenv/smarter_score_batcher/bin/activate
PIDFILE="/var/run/smarter_score_batcher/file-monitor-smarter_score_batcher.pid"
FILE_MONITOR="python -m smarter_score_batcher.trigger.file_monitor -d -p $PIDFILE"

start() {
	echo -n "Starting file-monitor-smarter_score_batcher: "
	daemon --user celery $FILE_MONITOR
	echo
	RETVAL=$?
}

stop() {
	echo -n "Stopping file-monitor-smarter_score_batcher: "
	killproc -p $PIDFILE
	echo
	RETVAL=$?
}

check_status() {
    echo -n "Checking file-monitor-smarter_score_batcher is running..."
    PID=`ps aux | grep file_monitor | grep -v grep | awk '{print $2}'`
    if [ -z "$PID" ];
    then
        echo -n "file-monitor-smarter_score_batcher is not running"
        echo
    else
        echo -n "file-monitor-smarter_score_batcher is running (pid $PID)"
        echo
    fi
}

case $1 in
	start)
		start
	;;
	stop)
		stop
	;;
	restart)
	    stop
	    start
	;;
	status)
	    check_status
	;;
	*)

	echo $"Usage: file-monitor-smarter_score_batcher {start|stop|restart|stop}"
	exit 2
esac
deactivate
exit $RETVAL
