#!/bin/bash
# (c) 2014 Amplify Education, Inc. All rights reserved, subject to the license
# below.
#
# Education agencies that are members of the Smarter Balanced Assessment
# Consortium as of August 1, 2014 are granted a worldwide, non-exclusive, fully
# paid-up, royalty-free, perpetual license, to access, use, execute, reproduce,
# display, distribute, perform and create derivative works of the software
# included in the Reporting Platform, including the source code to such software.
# This license includes the right to grant sublicenses by such consortium members
# to third party vendors solely for the purpose of performing services on behalf
# of such consortium member educational agencies.

#
# chkconfig: 345 90 10

# Source function library.
. /etc/rc.d/init.d/functions
#. /opt/virtualenv/smarter/bin/activate
CONF="/var/lib/pgsql/repmgr.conf"
PIDFILE="/var/run/repmgrd/repmgrd.pid"
LOG="/var/log/repmgrd/repmgr.log"
REPMGRD="/usr/pgsql-9.2/bin/repmgrd -f $CONF -d -p $PIDFILE --monitoring-history --verbose > $LOG 2>&1 &"
DAEMON_COREFILE_LIMIT="unlimited"

start() {
        echo -n "Starting repmgrd: "
        daemon --user=postgres $REPMGRD
        RETVAL=$?
}

stop() {
        echo -n "Stopping repmgrd: "
        killproc -p $PIDFILE
        RETVAL=$?
}
case $1 in
        start)
                start
        ;;
        stop)
                stop
        ;;
        *)

        echo $"Usage: repmgrd {start|stop}"
        exit 2
esac
exit $RETVAL

