#!/bin/bash
# (c) 2014 Amplify Education, Inc. All rights reserved, subject to the license
# below.
#
# Education agencies that are members of the Smarter Balanced Assessment
# Consortium as of August 1, 2014 are granted a worldwide, non-exclusive, fully
# paid-up, royalty-free, perpetual license, to access, use, execute, reproduce,
# display, distribute, perform and create derivative works of the software
# included in the Reporting Platform, including the source code to such software.
# This license includes the right to grant sublicenses by such consortium members
# to third party vendors solely for the purpose of performing services on behalf
# of such consortium member educational agencies.

#
# chkconfig: 345 90 10

# Source function library.
. /etc/rc.d/init.d/functions
PIDFILE="/var/run/edudl2-file-grabber/edudl2-file-grabber.pid"
EDUDL2_TRIGGER=". /opt/virtualenv/udl2/bin/activate; python -m edudl2.udl2_util.file_grabber -d -p $PIDFILE"

start() {
	echo -n "Starting edudl2 file grabber: "
	daemon --user udl2 $EDUDL2_TRIGGER
	echo
	RETVAL=$?
}

stop() {
	echo -n "Stopping edudl2 file grabber: "
	killproc -p $PIDFILE
	echo
	RETVAL=$?
}

check_status() {
    echo -n "Checking edudl2-file-grabber is running..."
    PID=`ps aux | grep file_grabber | grep -v grep | awk '{print $2}'`
    if [ -z "$PID" ];
    then
        echo -n "edudl2-file-grabber is not running"
        echo
    else
        echo -n "edudl2-file-grabber is running (pid $PID)"
        echo
    fi
}

case $1 in
	start)
		start
	;;
	stop)
		stop
	;;
	restart)
	    stop
	    start
	;;
	status)
	    check_status
	;;
	*)

	echo $"Usage: edudl2-file-grabber {start|stop|restart|status}"
	exit 2
esac
exit $RETVAL
