#!/bin/bash
#
# chkconfig: 345 90 10

# Source function library.
. /etc/rc.d/init.d/functions
PIDFILE="/var/run/edudl2/edudl2-grabber.pid"
EDUDL2_TRIGGER=". /opt/virtualenv/udl2/bin/activate; python -m edudl2.udl2_util.file_grabber -d -p $PIDFILE"

start() {
	echo -n "Starting file grabber: "
	daemon --user udl2 $EDUDL2_TRIGGER
	RETVAL=$?
}

stop() {
	echo -n "Stopping edudl2 trigger: "
	killproc -p $PIDFILE
	RETVAL=$?
}
case $1 in
	start)
		start
	;;
	stop)
		stop
	;;
	*)

	echo $"Usage: edudl2-file-grabber {start|stop}"
	exit 2
esac
exit $RETVAL
