__author__ = 'npandey'


class AttributeFieldConstants():

    ACADEMIC_YEAR = 'academic_year'
    STATE_NAME = 'state_name'
    DISTRICT_NAME = 'district_name'
    SCHOOL_NAME = 'school_name'
    STATE_CODE = 'state_code'
    DISTRICT_GUID = 'district_guid'
    SCHOOL_GUID = 'school_guid'
    GENDER = 'gender'
    HISPANIC_ETH = 'dmg_eth_hsp'
    AMERICAN_INDIAN = 'dmg_eth_ami'
    ASIAN = 'dmg_eth_asn'
    AFRICAN_AMERICAN = 'dmg_eth_blk'
    PACIFIC = 'dmg_eth_pcf'
    WHITE = 'dmg_eth_wht'
    MULTI_RACE = 'dmg_multi_race'
    IDEA_INDICATOR = 'dmg_prg_iep'
    LEP_STATUS = 'dmg_prg_lep'
    SECTION_504_STATUS = 'dmg_prg_504'
    ECON_DISADV_STATUS = 'dmg_sts_ecd'
    MIGRANT_STATUS = 'dmg_sts_mig'
    GRADE = 'enrl_grade'


class AttributeValueConstants():
    MALE = 'male'
    FEMALE = 'female'
    GRADEK = 'KG'
    GRADE1 = '01'
    GRADE2 = '02'
    GRADE3 = '03'
    GRADE4 = '04'
    GRADE5 = '05'
    GRADE6 = '06'
    GRADE7 = '07'
    GRADE8 = '08'
    GRADE9 = '09'
    GRADE10 = '10'
    GRADE11 = '11'
    GRADE12 = '12'
