fs = require 'fs'
walk = require 'walk'
require 'flour'
path = require 'path'
util = require 'util'
require 'colors'

coffeepath = 'coffee'
jspath = 'js'

buildCoffe = (source) ->
    destDir = path.dirname source.replace(coffeepath, jspath)
    mkdir destDir
    basename = path.basename source, '.coffee'
    if path.extname(source) == '.coffee'
        compile source, path.join(destDir, basename + '.js')
    else
        fs.createReadStream(source).pipe(fs.createWriteStream path.join(destDir, basename))

mkdir = (destDir) ->
    if not fs.existsSync destDir   
        fs.mkdirSync destDir, '0755'
    walker = walk.walkSync destDir
    walker.on 'directory', (root, dirStat, next) ->
        dir = path.join root, dirStat.name
        if not fs.existsSync dir   
            fs.mkdirSync dir, '0755'
        next
        
walkDir = (srcDir, fn) ->
    walker = walk.walkSync srcDir
    walker.on 'file', (root, fileStat, next) ->
        fn path.join(root, fileStat.name)
        next

task 'build:coffee', ->
    walkDir coffeepath, (source) -> buildCoffe source

task 'build:less', ->
    compile 'less/style.less', 'css/style.css'

task 'build', ->
    invoke 'build:coffee'
    invoke 'build:less'

task 'watch', ->
    invoke 'build'
    walkDir coffeepath, (source) -> watch source, ->  buildCoffe source

    watch 'less/*.less', ->  invoke 'build:less'

task 'lint', 'Check javascript syntax', ->
    lint 'js/*.js'