"""
The configuration for student demographic distributions.

"""

HAS_EMAIL_ADDRESS_RATE = .8
HAS_PHYSICAL_ADDRESS_RATE = .95
HAS_ADDRESS_LINE_2_RATE = .3

STUDENT_HOLD_BACK_RATE = .02  # 2% of students will be held back in their grade for a new year
STUDENT_DROP_OUT_RATE = .5  # 50% of students drop out if not advanced to the next grade
STUDENT_TRANSFER_RATE = .05  # 5% of students will move to a new school in the district without needing to

DEMOGRAPHICS = {
    'california':
        {'1': {'gender': {'male': {'name': 'Male', 'perc': .5134},
                          'female': {'name': 'Female', 'perc': .4866}},
               'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .0059},
                             'black': {'name': 'Black or African American', 'perc': .0594},
                             'hispanic': {'name': 'Hispanic or Latino', 'perc': .5356},
                             'asian': {'name': 'Asian', 'perc': .089},
                             'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander', 'perc': .0054},
                             'white': {'name': 'White', 'perc': .2492},
                             'multi': {'name': 'Multiethnic', 'perc': .0273},
                             'none': {'name': 'Not Stated', 'perc': .0057}},
               'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .11},
               '504': {'name': '504 Plan', 'perc': .07},
               'lep': {'name': 'LEP', 'perc': .301},
               'idea': {'name': 'IDEA Indicator', 'perc': .1},
               'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .53},
               'migrant': {'name': 'Migrant Status', 'perc': .0355}
               },
         '2': {'gender': {'male': {'name': 'Male', 'perc': .5134},
                          'female': {'name': 'Female', 'perc': .4866}},
               'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .0059},
                             'black': {'name': 'Black or African American', 'perc': .0594},
                             'hispanic': {'name': 'Hispanic or Latino', 'perc': .5356},
                             'asian': {'name': 'Asian', 'perc': .089},
                             'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander', 'perc': .0054},
                             'white': {'name': 'White', 'perc': .2492},
                             'multi': {'name': 'Multiethnic', 'perc': .0273},
                             'none': {'name': 'Not Stated', 'perc': .0057}},
               'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .11},
               '504': {'name': '504 Plan', 'perc': .07},
               'lep': {'name': 'LEP', 'perc': .301},
               'idea': {'name': 'IDEA Indicator', 'perc': .1},
               'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .53},
               'migrant': {'name': 'Migrant Status', 'perc': .0355}
               },
         '3': {'gender': {'male': {'name': 'Male', 'perc': .5134},
                          'female': {'name': 'Female', 'perc': .4866}},
               'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .0059},
                             'black': {'name': 'Black or African American', 'perc': .0594},
                             'hispanic': {'name': 'Hispanic or Latino', 'perc': .5356},
                             'asian': {'name': 'Asian', 'perc': .089},
                             'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander', 'perc': .0054},
                             'white': {'name': 'White', 'perc': .2492},
                             'multi': {'name': 'Multiethnic', 'perc': .0273},
                             'none': {'name': 'Not Stated', 'perc': .0057}},
               'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .11},
               '504': {'name': '504 Plan', 'perc': .07},
               'lep': {'name': 'LEP', 'perc': .301},
               'idea': {'name': 'IDEA Indicator', 'perc': .1},
               'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .53},
               'migrant': {'name': 'Migrant Status', 'perc': .0355}
               },
         '4': {'gender': {'male': {'name': 'Male', 'perc': .5125},
                          'female': {'name': 'Female', 'perc': .4875}},
               'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .006},
                             'black': {'name': 'Black or African American', 'perc': .0607},
                             'hispanic': {'name': 'Hispanic or Latino', 'perc': .5314},
                             'asian': {'name': 'Asian', 'perc': .0893},
                             'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander', 'perc': .0053},
                             'white': {'name': 'White', 'perc': .2526},
                             'multi': {'name': 'Multiethnic', 'perc': .024},
                             'none': {'name': 'Not Stated', 'perc': .006}},
               'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .11},
               '504': {'name': '504 Plan', 'perc': .07},
               'lep': {'name': 'LEP', 'perc': .253},
               'idea': {'name': 'IDEA Indicator', 'perc': .1},
               'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .53},
               'migrant': {'name': 'Migrant Status', 'perc': .0355}
               },
         '5': {'gender': {'male': {'name': 'Male', 'perc': .5117},
                          'female': {'name': 'Female', 'perc': .4883}},
               'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .0063},
                             'black': {'name': 'Black or African American', 'perc': .0631},
                             'hispanic': {'name': 'Hispanic or Latino', 'perc': .5309},
                             'asian': {'name': 'Asian', 'perc': .0877},
                             'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander', 'perc': .0055},
                             'white': {'name': 'White', 'perc': .2529},
                             'multi': {'name': 'Multiethnic', 'perc': .0227},
                             'none': {'name': 'Not Stated', 'perc': .0059}},
               'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .11},
               '504': {'name': '504 Plan', 'perc': .07},
               'lep': {'name': 'LEP', 'perc': .203},
               'idea': {'name': 'IDEA Indicator', 'perc': .1},
               'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .53},
               'migrant': {'name': 'Migrant Status', 'perc': .0355}
               },
         '6': {'gender': {'male': {'name': 'Male', 'perc': .5126},
                          'female': {'name': 'Female', 'perc': .4874}},
               'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .0062},
                             'black': {'name': 'Black or African American', 'perc': .0649},
                             'hispanic': {'name': 'Hispanic or Latino', 'perc': .5282},
                             'asian': {'name': 'Asian', 'perc': .0872},
                             'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander', 'perc': .0053},
                             'white': {'name': 'White', 'perc': .2536},
                             'multi': {'name': 'Multiethnic', 'perc': .0216},
                             'none': {'name': 'Not Stated', 'perc': .0069}},
               'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .11},
               '504': {'name': '504 Plan', 'perc': .07},
               'lep': {'name': 'LEP', 'perc': .17},
               'idea': {'name': 'IDEA Indicator', 'perc': .1},
               'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .53},
               'migrant': {'name': 'Migrant Status', 'perc': .0355}
               },
         '7': {'gender': {'male': {'name': 'Male', 'perc': .5132},
                          'female': {'name': 'Female', 'perc': .4868}},
               'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .0066},
                             'black': {'name': 'Black or African American', 'perc': .0652},
                             'hispanic': {'name': 'Hispanic or Latino', 'perc': .5228},
                             'asian': {'name': 'Asian', 'perc': .09},
                             'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander', 'perc': .0056},
                             'white': {'name': 'White', 'perc': .2567},
                             'multi': {'name': 'Multiethnic', 'perc': .0211},
                             'none': {'name': 'Not Stated', 'perc': .0058}},
               'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .11},
               '504': {'name': '504 Plan', 'perc': .07},
               'lep': {'name': 'LEP', 'perc': .149},
               'idea': {'name': 'IDEA Indicator', 'perc': .1},
               'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .53},
               'migrant': {'name': 'Migrant Status', 'perc': .0355}
               },
         '8': {'gender': {'male': {'name': 'Male', 'perc': .5137},
                          'female': {'name': 'Female', 'perc': .4863}},
               'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .0067},
                             'black': {'name': 'Black or African American', 'perc': .0676},
                             'hispanic': {'name': 'Hispanic or Latino', 'perc': .5182},
                             'asian': {'name': 'Asian', 'perc': .0848},
                             'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander', 'perc': .0056},
                             'white': {'name': 'White', 'perc': .2635},
                             'multi': {'name': 'Multiethnic', 'perc': .0205},
                             'none': {'name': 'Not Stated', 'perc': .0054}},
               'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .11},
               '504': {'name': '504 Plan', 'perc': .07},
               'lep': {'name': 'LEP', 'perc': .128},
               'idea': {'name': 'IDEA Indicator', 'perc': .1},
               'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .53},
               'migrant': {'name': 'Migrant Status', 'perc': .0355}
               },
         '9': {'gender': {'male': {'name': 'Male', 'perc': .5112},
                          'female': {'name': 'Female', 'perc': .4888}},
               'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .0074},
                             'black': {'name': 'Black or African American', 'perc': .067},
                             'hispanic': {'name': 'Hispanic or Latino', 'perc': .4979},
                             'asian': {'name': 'Asian', 'perc': .0908},
                             'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander', 'perc': .0057},
                             'white': {'name': 'White', 'perc': .2758},
                             'multi': {'name': 'Multiethnic', 'perc': .0196},
                             'none': {'name': 'Not Stated', 'perc': .0071}},
               'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .11},
               '504': {'name': '504 Plan', 'perc': .07},
               'lep': {'name': 'LEP', 'perc': .116},
               'idea': {'name': 'IDEA Indicator', 'perc': .1},
               'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .53},
               'migrant': {'name': 'Migrant Status', 'perc': .0355}
               },
         '10': {'gender': {'male': {'name': 'Male', 'perc': .5112},
                           'female': {'name': 'Female', 'perc': .4888}},
                'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .0074},
                              'black': {'name': 'Black or African American', 'perc': .067},
                              'hispanic': {'name': 'Hispanic or Latino', 'perc': .4979},
                              'asian': {'name': 'Asian', 'perc': .0908},
                              'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander', 'perc': .0057},
                              'white': {'name': 'White', 'perc': .2758},
                              'multi': {'name': 'Multiethnic', 'perc': .0196},
                              'none': {'name': 'Not Stated', 'perc': .0071}},
                'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .11},
                '504': {'name': '504 Plan', 'perc': .07},
                'lep': {'name': 'LEP', 'perc': .116},
                'idea': {'name': 'IDEA Indicator', 'perc': .1},
                'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .53},
                'migrant': {'name': 'Migrant Status', 'perc': .0355}
                },
         '11': {'gender': {'male': {'name': 'Male', 'perc': .5112},
                           'female': {'name': 'Female', 'perc': .4888}},
                'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .0074},
                              'black': {'name': 'Black or African American', 'perc': .067},
                              'hispanic': {'name': 'Hispanic or Latino', 'perc': .4979},
                              'asian': {'name': 'Asian', 'perc': .0908},
                              'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander', 'perc': .0057},
                              'white': {'name': 'White', 'perc': .2758},
                              'multi': {'name': 'Multiethnic', 'perc': .0196},
                              'none': {'name': 'Not Stated', 'perc': .0071}},
                'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .11},
                '504': {'name': '504 Plan', 'perc': .07},
                'lep': {'name': 'LEP', 'perc': .116},
                'idea': {'name': 'IDEA Indicator', 'perc': .1},
                'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .53},
                'migrant': {'name': 'Migrant Status', 'perc': .0355}
                },
         '12': {'gender': {'male': {'name': 'Male', 'perc': .5112},
                           'female': {'name': 'Female', 'perc': .4888}},
                'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .0074},
                              'black': {'name': 'Black or African American', 'perc': .067},
                              'hispanic': {'name': 'Hispanic or Latino', 'perc': .4979},
                              'asian': {'name': 'Asian', 'perc': .0908},
                              'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander', 'perc': .0057},
                              'white': {'name': 'White', 'perc': .2758},
                              'multi': {'name': 'Multiethnic', 'perc': .0196},
                              'none': {'name': 'Not Stated', 'perc': .0071}},
                'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .11},
                '504': {'name': '504 Plan', 'perc': .07},
                'lep': {'name': 'LEP', 'perc': .116},
                'idea': {'name': 'IDEA Indicator', 'perc': .1},
                'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .53},
                'migrant': {'name': 'Migrant Status', 'perc': .0355}
                }
         },
    'typical1': {
        '1': {'gender': {'male': {'name': 'Male', 'perc': .50},
                         'female': {'name': 'Female', 'perc': .48},
                         'none': {'name': 'Not Stated', 'perc': .02}},
              'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .01},
                            'black': {'name': 'Black or African American', 'perc': .18},
                            'hispanic': {'name': 'Hispanic or Latino', 'perc': .23},
                            'asian': {'name': 'Asian', 'perc': .07},
                            'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander', 'perc': .03},
                            'white': {'name': 'White', 'perc': .45},
                            'multi': {'name': 'Multiethnic', 'perc': .01},
                            'none': {'name': 'Not Stated', 'perc': .02}},
              'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .15},
              '504': {'name': '504 Plan', 'perc': .07},
              'lep': {'name': 'LEP', 'perc': .09},
              'idea': {'name': 'IDEA Indicator', 'perc': .1},
              'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .57},
              'migrant': {'name': 'Migrant Status', 'perc': .0355}
              },
        '2': {'gender': {'male': {'name': 'Male', 'perc': .50},
                         'female': {'name': 'Female', 'perc': .48},
                         'none': {'name': 'Not Stated', 'perc': .02}},
              'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .01},
                            'black': {'name': 'Black or African American', 'perc': .18},
                            'hispanic': {'name': 'Hispanic or Latino', 'perc': .23},
                            'asian': {'name': 'Asian', 'perc': .07},
                            'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander', 'perc': .03},
                            'white': {'name': 'White', 'perc': .45},
                            'multi': {'name': 'Multiethnic', 'perc': .01},
                            'none': {'name': 'Not Stated', 'perc': .02}},
              'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .15},
              '504': {'name': '504 Plan', 'perc': .07},
              'lep': {'name': 'LEP', 'perc': .09},
              'idea': {'name': 'IDEA Indicator', 'perc': .1},
              'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .57},
              'migrant': {'name': 'Migrant Status', 'perc': .0355}
              },
        '3': {'gender': {'male': {'name': 'Male', 'perc': .50},
                         'female': {'name': 'Female', 'perc': .48},
                         'none': {'name': 'Not Stated', 'perc': .02}},
              'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .01},
                            'black': {'name': 'Black or African American', 'perc': .18},
                            'hispanic': {'name': 'Hispanic or Latino', 'perc': .23},
                            'asian': {'name': 'Asian', 'perc': .07},
                            'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander', 'perc': .03},
                            'white': {'name': 'White', 'perc': .45},
                            'multi': {'name': 'Multiethnic', 'perc': .01},
                            'none': {'name': 'Not Stated', 'perc': .02}},
              'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .15},
              '504': {'name': '504 Plan', 'perc': .07},
              'lep': {'name': 'LEP', 'perc': .09},
              'idea': {'name': 'IDEA Indicator', 'perc': .1},
              'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .57},
              'migrant': {'name': 'Migrant Status', 'perc': .0355}
              },
        '4': {'gender': {'male': {'name': 'Male', 'perc': .50},
                         'female': {'name': 'Female', 'perc': .49},
                         'none': {'name': 'Not Stated', 'perc': .01}},
              'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .01},
                            'black': {'name': 'Black or African American', 'perc': .17},
                            'hispanic': {'name': 'Hispanic or Latino', 'perc': .24},
                            'asian': {'name': 'Asian', 'perc': .07},
                            'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander', 'perc': .02},
                            'white': {'name': 'White', 'perc': .46},
                            'multi': {'name': 'Multiethnic', 'perc': .01},
                            'none': {'name': 'Not Stated', 'perc': .02}},
              'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .15},
              '504': {'name': '504 Plan', 'perc': .07},
              'lep': {'name': 'LEP', 'perc': .09},
              'idea': {'name': 'IDEA Indicator', 'perc': .1},
              'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .57},
              'migrant': {'name': 'Migrant Status', 'perc': .0355}
              },
        '5': {'gender': {'male': {'name': 'Male', 'perc': .50},
                         'female': {'name': 'Female', 'perc': .49},
                         'none': {'name': 'Not Stated', 'perc': .01}},
              'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': 0},
                            'black': {'name': 'Black or African American', 'perc': .19},
                            'hispanic': {'name': 'Hispanic or Latino', 'perc': .20},
                            'asian': {'name': 'Asian', 'perc': .08},
                            'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander', 'perc': .02},
                            'white': {'name': 'White', 'perc': .48},
                            'multi': {'name': 'Multiethnic', 'perc': .01},
                            'none': {'name': 'Not Stated', 'perc': .02}},
              'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .16},
              '504': {'name': '504 Plan', 'perc': .08},
              'lep': {'name': 'LEP', 'perc': .08},
              'idea': {'name': 'IDEA Indicator', 'perc': .1},
              'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .56},
              'migrant': {'name': 'Migrant Status', 'perc': .0355}
              },
        '6': {'gender': {'male': {'name': 'Male', 'perc': .50},
                         'female': {'name': 'Female', 'perc': .49},
                         'none': {'name': 'Not Stated', 'perc': .01}},
              'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': 0},
                            'black': {'name': 'Black or African American', 'perc': .19},
                            'hispanic': {'name': 'Hispanic or Latino', 'perc': .20},
                            'asian': {'name': 'Asian', 'perc': .09},
                            'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander', 'perc': .02},
                            'white': {'name': 'White', 'perc': .47},
                            'multi': {'name': 'Multiethnic', 'perc': .01},
                            'none': {'name': 'Not Stated', 'perc': .02}},
              'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .16},
              '504': {'name': '504 Plan', 'perc': .08},
              'lep': {'name': 'LEP', 'perc': .06},
              'idea': {'name': 'IDEA Indicator', 'perc': .1},
              'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .54},
              'migrant': {'name': 'Migrant Status', 'perc': .0355}
              },
        '7': {'gender': {'male': {'name': 'Male', 'perc': .51},
                         'female': {'name': 'Female', 'perc': .48},
                         'none': {'name': 'Not Stated', 'perc': .01}},
              'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .01},
                            'black': {'name': 'Black or African American', 'perc': .19},
                            'hispanic': {'name': 'Hispanic or Latino', 'perc': .20},
                            'asian': {'name': 'Asian', 'perc': .08},
                            'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander', 'perc': .01},
                            'white': {'name': 'White', 'perc': .48},
                            'multi': {'name': 'Multiethnic', 'perc': .01},
                            'none': {'name': 'Not Stated', 'perc': .02}},
              'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .16},
              '504': {'name': '504 Plan', 'perc': .08},
              'lep': {'name': 'LEP', 'perc': .06},
              'idea': {'name': 'IDEA Indicator', 'perc': .1},
              'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .53},
              'migrant': {'name': 'Migrant Status', 'perc': .0355}
              },
        '8': {'gender': {'male': {'name': 'Male', 'perc': .50},
                         'female': {'name': 'Female', 'perc': .49},
                         'none': {'name': 'Not Stated', 'perc': .01}},
              'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .01},
                            'black': {'name': 'Black or African American', 'perc': .18},
                            'hispanic': {'name': 'Hispanic or Latino', 'perc': .20},
                            'asian': {'name': 'Asian', 'perc': .08},
                            'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander', 'perc': .02},
                            'white': {'name': 'White', 'perc': .48},
                            'multi': {'name': 'Multiethnic', 'perc': .01},
                            'none': {'name': 'Not Stated', 'perc': .02}},
              'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .16},
              '504': {'name': '504 Plan', 'perc': .08},
              'lep': {'name': 'LEP', 'perc': .06},
              'idea': {'name': 'IDEA Indicator', 'perc': .1},
              'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .52},
              'migrant': {'name': 'Migrant Status', 'perc': .0355}
              },
        '9': {'gender': {'male': {'name': 'Male', 'perc': .50},
                         'female': {'name': 'Female', 'perc': .48},
                         'none': {'name': 'Not Stated', 'perc': .02}},
              'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .01},
                            'black': {'name': 'Black or African American', 'perc': .18},
                            'hispanic': {'name': 'Hispanic or Latino', 'perc': .23},
                            'asian': {'name': 'Asian', 'perc': .07},
                            'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander', 'perc': .03},
                            'white': {'name': 'White', 'perc': .45},
                            'multi': {'name': 'Multiethnic', 'perc': .01},
                            'none': {'name': 'Not Stated', 'perc': .02}},
              'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .15},
              '504': {'name': '504 Plan', 'perc': .07},
              'lep': {'name': 'LEP', 'perc': .09},
              'idea': {'name': 'IDEA Indicator', 'perc': .1},
              'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .57},
              'migrant': {'name': 'Migrant Status', 'perc': .0355}
              },
        '10': {'gender': {'male': {'name': 'Male', 'perc': .50},
                          'female': {'name': 'Female', 'perc': .48},
                          'none': {'name': 'Not Stated', 'perc': .02}},
               'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .01},
                             'black': {'name': 'Black or African American', 'perc': .18},
                             'hispanic': {'name': 'Hispanic or Latino', 'perc': .23},
                             'asian': {'name': 'Asian', 'perc': .07},
                             'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander', 'perc': .03},
                             'white': {'name': 'White', 'perc': .45},
                             'multi': {'name': 'Multiethnic', 'perc': .01},
                             'none': {'name': 'Not Stated', 'perc': .02}},
               'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .15},
               '504': {'name': '504 Plan', 'perc': .07},
               'lep': {'name': 'LEP', 'perc': .09},
               'idea': {'name': 'IDEA Indicator', 'perc': .1},
               'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .57},
               'migrant': {'name': 'Migrant Status', 'perc': .0355}
               },
        '11': {'gender': {'male': {'name': 'Male', 'perc': .51},
                          'female': {'name': 'Female', 'perc': .47},
                          'none': {'name': 'Not Stated', 'perc': .02}},
               'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .01},
                             'black': {'name': 'Black or African American', 'perc': .19},
                             'hispanic': {'name': 'Hispanic or Latino', 'perc': .20},
                             'asian': {'name': 'Asian', 'perc': .08},
                             'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander', 'perc': .02},
                             'white': {'name': 'White', 'perc': .47},
                             'multi': {'name': 'Multiethnic', 'perc': .01},
                             'none': {'name': 'Not Stated', 'perc': .02}},
               'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .16},
               '504': {'name': '504 Plan', 'perc': .08},
               'lep': {'name': 'LEP', 'perc': .06},
               'idea': {'name': 'IDEA Indicator', 'perc': .1},
               'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .52},
               'migrant': {'name': 'Migrant Status', 'perc': .0355}
               },
        '12': {'gender': {'male': {'name': 'Male', 'perc': .51},
                          'female': {'name': 'Female', 'perc': .47},
                          'none': {'name': 'Not Stated', 'perc': .2}},
               'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .01},
                             'black': {'name': 'Black or African American', 'perc': .19},
                             'hispanic': {'name': 'Hispanic or Latino', 'perc': .20},
                             'asian': {'name': 'Asian', 'perc': .08},
                             'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander', 'perc': .02},
                             'white': {'name': 'White', 'perc': .47},
                             'multi': {'name': 'Multiethnic', 'perc': .01},
                             'none': {'name': 'Not Stated', 'perc': .02}},
               'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .16},
               '504': {'name': '504 Plan', 'perc': .08},
               'lep': {'name': 'LEP', 'perc': .06},
               'idea': {'name': 'IDEA Indicator', 'perc': .1},
               'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .52},
               'migrant': {'name': 'Migrant Status', 'perc': .0355}
               }
    }
}
