"""
The configuration for student demographic distributions.

:author: nestep
:date: February 22, 2014
"""

HAS_EMAIL_ADDRESS_RATE = .8
HAS_PHYSICAL_ADDRESS_RATE = .95
HAS_ADDRESS_LINE_2_RATE = .3

DEMOGRAPHICS = {'typical1': {'1': {'gender': {'male': {'name': 'Male', 'perc': .50},
                                              'female': {'name': 'Female', 'perc': .48},
                                              'none': {'name': 'Not Stated', 'perc': .02}},
                                   'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .01},
                                                 'black': {'name': 'Black or African American', 'perc': .18},
                                                 'hispanic': {'name': 'Hispanic or Latino', 'perc': .23},
                                                 'asian': {'name': 'Asian', 'perc': .07},
                                                 'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander',
                                                             'perc': .03},
                                                 'white': {'name': 'White', 'perc': .45},
                                                 'multi': {'name': 'Multiethnic', 'perc': .01},
                                                 'none': {'name': 'Not Stated', 'perc': .02}},
                                   'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .15},
                                   '504': {'name': '504 Plan', 'perc': .07},
                                   'lep': {'name': 'LEP', 'perc': .09},
                                   'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .57}
                                   },
                             '2': {'gender': {'male': {'name': 'Male', 'perc': .50},
                                              'female': {'name': 'Female', 'perc': .48},
                                              'none': {'name': 'Not Stated', 'perc': .02}},
                                   'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .01},
                                                 'black': {'name': 'Black or African American', 'perc': .18},
                                                 'hispanic': {'name': 'Hispanic or Latino', 'perc': .23},
                                                 'asian': {'name': 'Asian', 'perc': .07},
                                                 'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander',
                                                             'perc': .03},
                                                 'white': {'name': 'White', 'perc': .45},
                                                 'multi': {'name': 'Multiethnic', 'perc': .01},
                                                 'none': {'name': 'Not Stated', 'perc': .02}},
                                   'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .15},
                                   '504': {'name': '504 Plan', 'perc': .07},
                                   'lep': {'name': 'LEP', 'perc': .09},
                                   'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .57}
                                   },
                             '3': {'gender': {'male': {'name': 'Male', 'perc': .50},
                                              'female': {'name': 'Female', 'perc': .48},
                                              'none': {'name': 'Not Stated', 'perc': .02}},
                                   'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .01},
                                                 'black': {'name': 'Black or African American', 'perc': .18},
                                                 'hispanic': {'name': 'Hispanic or Latino', 'perc': .23},
                                                 'asian': {'name': 'Asian', 'perc': .07},
                                                 'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander',
                                                             'perc': .03},
                                                 'white': {'name': 'White', 'perc': .45},
                                                 'multi': {'name': 'Multiethnic', 'perc': .01},
                                                 'none': {'name': 'Not Stated', 'perc': .02}},
                                   'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .15},
                                   '504': {'name': '504 Plan', 'perc': .07},
                                   'lep': {'name': 'LEP', 'perc': .09},
                                   'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .57}
                                   },
                             '4': {'gender': {'male': {'name': 'Male', 'perc': .50},
                                              'female': {'name': 'Female', 'perc': .49},
                                              'none': {'name': 'Not Stated', 'perc': .01}},
                                   'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .01},
                                                 'black': {'name': 'Black or African American', 'perc': .17},
                                                 'hispanic': {'name': 'Hispanic or Latino', 'perc': .24},
                                                 'asian': {'name': 'Asian', 'perc': .07},
                                                 'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander',
                                                             'perc': .02},
                                                 'white': {'name': 'White', 'perc': .46},
                                                 'multi': {'name': 'Multiethnic', 'perc': .01},
                                                 'none': {'name': 'Not Stated', 'perc': .02}},
                                   'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .15},
                                   '504': {'name': '504 Plan', 'perc': .07},
                                   'lep': {'name': 'LEP', 'perc': .09},
                                   'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .57}
                                   },
                             '5': {'gender': {'male': {'name': 'Male', 'perc': .50},
                                              'female': {'name': 'Female', 'perc': .49},
                                              'none': {'name': 'Not Stated', 'perc': .01}},
                                   'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': 0},
                                                 'black': {'name': 'Black or African American', 'perc': .19},
                                                 'hispanic': {'name': 'Hispanic or Latino', 'perc': .20},
                                                 'asian': {'name': 'Asian', 'perc': .08},
                                                 'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander',
                                                             'perc': .02},
                                                 'white': {'name': 'White', 'perc': .48},
                                                 'multi': {'name': 'Multiethnic', 'perc': .01},
                                                 'none': {'name': 'Not Stated', 'perc': .02}},
                                   'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .16},
                                   '504': {'name': '504 Plan', 'perc': .08},
                                   'lep': {'name': 'LEP', 'perc': .08},
                                   'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .56}
                                   },
                             '6': {'gender': {'male': {'name': 'Male', 'perc': .50},
                                              'female': {'name': 'Female', 'perc': .49},
                                              'none': {'name': 'Not Stated', 'perc': .01}},
                                   'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': 0},
                                                 'black': {'name': 'Black or African American', 'perc': .19},
                                                 'hispanic': {'name': 'Hispanic or Latino', 'perc': .20},
                                                 'asian': {'name': 'Asian', 'perc': .09},
                                                 'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander',
                                                             'perc': .02},
                                                 'white': {'name': 'White', 'perc': .47},
                                                 'multi': {'name': 'Multiethnic', 'perc': .01},
                                                 'none': {'name': 'Not Stated', 'perc': .02}},
                                   'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .16},
                                   '504': {'name': '504 Plan', 'perc': .08},
                                   'lep': {'name': 'LEP', 'perc': .06},
                                   'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .54}
                                   },
                             '7': {'gender': {'male': {'name': 'Male', 'perc': .51},
                                              'female': {'name': 'Female', 'perc': .48},
                                              'none': {'name': 'Not Stated', 'perc': .01}},
                                   'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .01},
                                                 'black': {'name': 'Black or African American', 'perc': .19},
                                                 'hispanic': {'name': 'Hispanic or Latino', 'perc': .20},
                                                 'asian': {'name': 'Asian', 'perc': .08},
                                                 'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander',
                                                             'perc': .01},
                                                 'white': {'name': 'White', 'perc': .48},
                                                 'multi': {'name': 'Multiethnic', 'perc': .01},
                                                 'none': {'name': 'Not Stated', 'perc': .02}},
                                   'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .16},
                                   '504': {'name': '504 Plan', 'perc': .08},
                                   'lep': {'name': 'LEP', 'perc': .06},
                                   'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .53}
                                   },
                             '8': {'gender': {'male': {'name': 'Male', 'perc': .50},
                                              'female': {'name': 'Female', 'perc': .49},
                                              'none': {'name': 'Not Stated', 'perc': .01}},
                                   'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .01},
                                                 'black': {'name': 'Black or African American', 'perc': .18},
                                                 'hispanic': {'name': 'Hispanic or Latino', 'perc': .20},
                                                 'asian': {'name': 'Asian', 'perc': .08},
                                                 'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander',
                                                             'perc': .02},
                                                 'white': {'name': 'White', 'perc': .48},
                                                 'multi': {'name': 'Multiethnic', 'perc': .01},
                                                 'none': {'name': 'Not Stated', 'perc': .02}},
                                   'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .16},
                                   '504': {'name': '504 Plan', 'perc': .08},
                                   'lep': {'name': 'LEP', 'perc': .06},
                                   'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .52}
                                   },
                             '9': {'gender': {'male': {'name': 'Male', 'perc': .50},
                                              'female': {'name': 'Female', 'perc': .48},
                                              'none': {'name': 'Not Stated', 'perc': .02}},
                                   'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .01},
                                                 'black': {'name': 'Black or African American', 'perc': .18},
                                                 'hispanic': {'name': 'Hispanic or Latino', 'perc': .23},
                                                 'asian': {'name': 'Asian', 'perc': .07},
                                                 'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander',
                                                             'perc': .03},
                                                 'white': {'name': 'White', 'perc': .45},
                                                 'multi': {'name': 'Multiethnic', 'perc': .01},
                                                 'none': {'name': 'Not Stated', 'perc': .02}},
                                   'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .15},
                                   '504': {'name': '504 Plan', 'perc': .07},
                                   'lep': {'name': 'LEP', 'perc': .09},
                                   'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .57}
                                   },
                             '10': {'gender': {'male': {'name': 'Male', 'perc': .50},
                                               'female': {'name': 'Female', 'perc': .48},
                                               'none': {'name': 'Not Stated', 'perc': .02}},
                                    'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .01},
                                                  'black': {'name': 'Black or African American', 'perc': .18},
                                                  'hispanic': {'name': 'Hispanic or Latino', 'perc': .23},
                                                  'asian': {'name': 'Asian', 'perc': .07},
                                                  'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander',
                                                              'perc': .03},
                                                  'white': {'name': 'White', 'perc': .45},
                                                  'multi': {'name': 'Multiethnic', 'perc': .01},
                                                  'none': {'name': 'Not Stated', 'perc': .02}},
                                    'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .15},
                                    '504': {'name': '504 Plan', 'perc': .07},
                                    'lep': {'name': 'LEP', 'perc': .09},
                                    'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .57}
                                    },
                             '11': {'gender': {'male': {'name': 'Male', 'perc': .51},
                                               'female': {'name': 'Female', 'perc': .47},
                                               'none': {'name': 'Not Stated', 'perc': .02}},
                                    'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .01},
                                                  'black': {'name': 'Black or African American', 'perc': .19},
                                                  'hispanic': {'name': 'Hispanic or Latino', 'perc': .20},
                                                  'asian': {'name': 'Asian', 'perc': .08},
                                                  'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander',
                                                              'perc': .02},
                                                  'white': {'name': 'White', 'perc': .47},
                                                  'multi': {'name': 'Multiethnic', 'perc': .01},
                                                  'none': {'name': 'Not Stated', 'perc': .02}},
                                    'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .16},
                                    '504': {'name': '504 Plan', 'perc': .08},
                                    'lep': {'name': 'LEP', 'perc': .06},
                                    'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .52}
                                    },
                             '12': {'gender': {'male': {'name': 'Male', 'perc': .51},
                                               'female': {'name': 'Female', 'perc': .47},
                                               'none': {'name': 'Not Stated', 'perc': .2}},
                                    'ethnicity': {'amer_ind': {'name': 'American Indian', 'perc': .01},
                                                  'black': {'name': 'Black or African American', 'perc': .19},
                                                  'hispanic': {'name': 'Hispanic or Latino', 'perc': .20},
                                                  'asian': {'name': 'Asian', 'perc': .08},
                                                  'pac_isl': {'name': 'Native Hawaiian/Other Pacific Islander',
                                                              'perc': .02},
                                                  'white': {'name': 'White', 'perc': .47},
                                                  'multi': {'name': 'Multiethnic', 'perc': .01},
                                                  'none': {'name': 'Not Stated', 'perc': .02}},
                                    'iep': {'name': 'Students with Disabilities (IEP)', 'perc': .16},
                                    '504': {'name': '504 Plan', 'perc': .08},
                                    'lep': {'name': 'LEP', 'perc': .06},
                                    'econ_dis': {'name': 'Economically Disadvantaged', 'perc': .52}
                                    }
                             }
                }

DISTRICT_LEVEL_STAFF_COUNT = 10
STUDENT_HOLD_BACK_RATE = .02  # 2% of students will be held back in their grade for a new year
STUDENT_DROP_OUT_RATE = .5  # 50% of students drop out if not advanced to the next grade
STUDENT_TRANSFER_RATE = .05  # 5% of students will move to a new school in the district without needing to
