// Generated by CoffeeScript 1.4.0
(function() {
  var showGuests;

  showGuests = function() {
    return $.get("attendees.js", function(response) {
      return $("#how-many-attendees").html("" + response + " attendees!");
    });
  };

  setInterval(showGuests, 1000);

}).call(this);
