__author__ = 'sravi'


class Constants():
    '''
    Constants related to edmigrate
    '''
    REPL_MGR_SCHEMA = 'repmgr_edware_pg_cluster'
    REPL_STATUS = 'repl_status'
    REPL_NODES = 'repl_nodes'
    REPL_NODE_CONN_INFO = 'conninfo'
    ID = 'id'
    REPL_STANDBY_NODE = 'standby_node'
    REPLICATION_LAG = 'replication_lag'
    APPLY_LAG = 'apply_lag'
    TIME_LAG = 'time_lag'
    SLAVE_GROUP_A = 'A'
    SLAVE_GROUP_B = 'B'
    FACT_ASMT_OUTCOME = 'fact_asmt_outcome'
    DIM_SECTION = 'dim_section'
    ASMNT_OUTCOME_REC_ID = 'asmnt_outcome_rec_id'
    WHERE_TAKEN_NAME = 'where_taken_name'
    STATUS = 'status'
    STATUS_CREATED = 'C'
    STATUS_DELETED = 'D'
