---
- hosts: $servers

  tasks:
    - name: uninstall smarter-dev if already installed
      action: command rpm -e smarter-dev
      sudo: yes
      ignore_errors: yes
    
    - name: uninstall smarter if already installed
      action: command rpm -e smarter
      sudo: yes
      ignore_errors: yes

    - name: do a yum clean
      action: command yum -d 0 clean all
      sudo: yes

    - name: run rpm install with latest rpm
      action: yum name=smarter state=latest
      sudo: yes
      when: rpm_name is not defined
    
    - name: run rpm install with explicit rpm
      action: yum name=$rpm_name state=installed 
      sudo: yes
      when: rpm_name is defined

    - name: generate ini file
      action: command /opt/virtualenv/bin/python generate_ini.py -e $ini_name chdir=/opt/edware/conf
      sudo: yes
      notify:
        - restart apache

  handlers:
    - name: restart apache
      action: service name=apache state=restarted
