# Abbreviations:
SI = 'Student Identifier'
AI = 'Assessment Identifiers'
OA = 'Overall'
CL = 'Claim'

# Column Headers and types:
# list index keeps the order of columns
# each tuple in list: (landing_zone_column_name, schema_column_name)
COLUMN_MAP_INFO = [('SI-state-code', 'state_code'),
                      ('SI-district-id', 'district_id'),
                      ('SI-school-id', 'school_id'),
                      ('SI-teacher-id', 'teacher_guid'),
                      ('SI-student-grade', 'enrl_grade'),
                      ('SI-section-id', 'section_guid'),
                      ('SI-student-id', 'student_id'),
                      ('AI-asmt-id', 'asmt_rec_id'),
                      ('AI-date-taken', 'date_taken'),
                      ('AI-where-taken', 'where_taken_id'),
                      ('OA-score', 'asmt_score'),
                      ('OA-CI-left', 'asmt_score_range_min'),
                      ('OA-CI-right', 'asmt_score_range_max'),
                      ('CL-1-claim', 'asmt_claim_1_score'),
                      ('CL-1-CI-left', 'asmt_claim_1_score_range_min'),
                      ('CL-1-CI-right', 'asmt_claim_1_score_range_max'),
                      ('CL-2-claim', 'asmt_claim_2_score'),
                      ('CL-2-CI-left', 'asmt_claim_2_score_range_min'),
                      ('CL-2-CI-right', 'asmt_claim_2_score_range_max'),
                      ('CL-3-claim', 'asmt_claim_3_score'),
                      ('CL-3-CI-left', 'asmt_claim_3_score_range_min'),
                      ('CL-3-CI-right', 'asmt_claim_3_score_range_max'),
                      ('CL-4-claim', 'asmt_claim_4_score'),
                      ('CL-4-CI-left', 'asmt_claim_4_score_range_min'),
                      ('CL-4-CI-right', 'asmt_claim_4_score_range_max'),
                      ]

COLUMN_MAP_INFO_2 = [('guid_asmt', 'dim_asmt', 'dim_asmt'),
                     ('guid_asmt_location', 'where_taken_id', 'fact_asmt_outcome'),
                     ('name_asmt_location', 'where_taken_name', 'fact_asmt_outcome'),
                     ('grade_asmt', 'asmt_grade', 'fact_asmt_outcome'),
                     ('name_state', 'state_name', 'dim_inst_hier'),
                     ('code_state', 'state_code', 'fact_asmt_outcome'),
                     ('guid_district', 'district_id', 'fact_asmt_outcome'),
                     ('name_district', 'district_name', 'dim_inst_hier'),
                     ('guid_school', 'school_id', 'fact_asmt_outcome'),
                     ('name_school', 'school_name', 'dim_inst_hier'),
                     ('type_school', 'school_category', 'dim_inst_hier'),
                     ('guid_student', 'student_id', 'fact_asmt_outcome'),
                     ('name_student_first', 'first_name', 'dim_student'),
                     ('name_student_middle', 'middle_name', 'dim_student'),
                     ('name_student_last', 'last_name', 'dim_student'),
                     ('address_student_line1', 'address_1', 'dim_student'),
                     ('address_student_line2', 'address_2', 'dim_student'),
                     ('address_student_city', 'city', 'dim_student'),
                     ('address_student_zip', 'zip_code', 'dim_student'),
                     ('gender_student', 'gender', 'dim_student'),
                     ('email_student', 'email', 'dim_student'),
                     ('dob_student', 'dob', 'dim_student'),
                     ('grade_enrolled', 'enrl_grade', 'fact_asmt_outcome'),
                     ('date_assessed', 'date_taken', 'fact_asmt_outcome'),
                     ('score_asmt', 'asmt_score', 'fact_asmt_outcome'),
                     ('score_asmt_min', 'asmt_score_range_min', 'fact_asmt_outcome'),
                     ('score_asmt_max', 'asmt_score_range_max', 'fact_asmt_outcome'),
                     ('score_claim_1', 'asmt_claim_1_score', 'fact_asmt_outcome'),
                     ('score_claim_1_min', 'asmt_claim_1_score_range_min', 'fact_asmt_outcome'),
                     ('score_claim_1_max', 'asmt_claim_1_score_range_max', 'fact_asmt_outcome'),
                     ('score_claim_2', 'asmt_claim_2_score', 'fact_asmt_outcome'),
                     ('score_claim_2_min', 'asmt_claim_2_score_range_min', 'fact_asmt_outcome'),
                     ('score_claim_2_max', 'asmt_claim_2_score_range_max', 'fact_asmt_outcome'),
                     ('score_claim_3', 'asmt_claim_3_score', 'fact_asmt_outcome'),
                     ('score_claim_3_min', 'asmt_claim_3_score_range_min', 'fact_asmt_outcome'),
                     ('score_claim_3_max', 'asmt_claim_3_score_range_max', 'fact_asmt_outcome'),
                     ('score_claim_4', 'asmt_claim_4_score', 'fact_asmt_outcome'),
                     ('score_claim_4_min', 'asmt_claim_4_score_range_min', 'fact_asmt_outcome'),
                     ('score_claim_4_max', 'asmt_claim_4_score_range_max', 'fact_asmt_outcome'),
                     ('guid_staff', 'teacher_guid', 'fact_asmt_outcome'),
                     ('name_staff_first', 'first_name', 'dim_staff'),
                     ('name_staff_middle', 'middle_name', 'dim_staff'),
                     ('name_staff_last', 'last_name', 'dim_staff'),
                     ('type_staff', 'hier_user_type', 'dim_staff'),
                     ]


COLUMN_MAP_INFO_3 = [
    ('dim_asmt', 'asmt_guid', 'guid_asmt'),
    ('fact_asmt_outcome', 'where_taken_id', 'guid_asmt_location'),
    ('fact_asmt_outcome', 'where_taken_name', 'name_asmt_location'),
    ('fact_asmt_outcome', 'asmt_grade', 'grade_asmt'),
    ('dim_inst_hier', 'state_name', 'name_state'),
    ('zdim_inst_hier', 'state_code', 'code_state'),
    ('dim_inst_hier', 'district_id', 'guid_district'),
    ('dim_inst_hier', 'district_name', 'name_district'),
    ('dim_inst_hier', 'school_id', 'guid_school'),
    ('dim_inst_hier', 'school_name', 'name_school'),
    ('dim_inst_hier', 'school_category', 'type_school'),
    ('dim_student', 'student_id', 'guid_student'),
    ('dim_student', 'first_name', 'name_student_first'),
    ('dim_student', 'middle_name', 'name_student_middle'),
    ('dim_student', 'last_name', 'name_student_last'),
    ('dim_student', 'address_1', 'address_student_line1'),
    ('dim_student', 'address_2', 'address_student_line2'),
    ('dim_student', 'city', 'address_student_city'),
    ('dim_student', 'zip_code', 'address_student_zip'),
    ('dim_student', 'gender', 'gender_student'),
    ('dim_student', 'email', 'email_student'),
    ('dim_student', 'dob', 'dob_student'),
    ('fact_asmt_outcome', 'enrl_grade', 'grade_enrolled'),
    ('fact_asmt_outcome', 'date_taken', 'date_assessed'),
    ('fact_asmt_outcome', 'asmt_score', 'score_asmt'),
    ('fact_asmt_outcome', 'asmt_score_range_min', 'score_asmt_min'),
    ('fact_asmt_outcome', 'asmt_score_range_max', 'score_asmt_max'),
    ('fact_asmt_outcome', 'asmt_perf_lvl', 'score_perf_level'),
    ('fact_asmt_outcome', 'asmt_claim_1_score', 'score_claim_1'),
    ('fact_asmt_outcome', 'asmt_claim_1_score_range_min', 'score_claim_1_min'),
    ('fact_asmt_outcome', 'asmt_claim_1_score_range_max', 'score_claim_1_max'),
    ('fact_asmt_outcome', 'asmt_claim_2_score', 'score_claim_2'),
    ('fact_asmt_outcome', 'asmt_claim_2_score_range_min', 'score_claim_2_min'),
    ('fact_asmt_outcome', 'asmt_claim_2_score_range_max', 'score_claim_2_max'),
    ('fact_asmt_outcome', 'asmt_claim_3_score', 'score_claim_3'),
    ('fact_asmt_outcome', 'asmt_claim_3_score_range_min', 'score_claim_3_min'),
    ('fact_asmt_outcome', 'asmt_claim_3_score_range_max', 'score_claim_3_max'),
    ('fact_asmt_outcome', 'asmt_claim_4_score', 'score_claim_4'),
    ('fact_asmt_outcome', 'asmt_claim_4_score_range_min', 'score_claim_4_min'),
    ('fact_asmt_outcome', 'asmt_claim_4_score_range_max', 'score_claim_4_max'),
    ('dim_staff', 'staff_guid', 'guid_staff'),
    ('dim_staff', 'first_name', 'name_staff_first'),
    ('dim_staff', 'middle_name', 'name_staff_middle'),
    ('dim_staff', 'last_name', 'name_staff_last'),
    ('dim_staff', 'hier_user_type', 'type_staff')]
